//go:build !ignore_autogenerated

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *ModelReference) DeepCopyInto(out *ModelReference) { *out = *in }
func (in *ModelReference) DeepCopy() *ModelReference {
	if in == nil {
		return nil
	}
	out := new(ModelReference)
	in.DeepCopyInto(out)
	return out
}
func (in *EngineSpec) DeepCopyInto(out *EngineSpec) {
	*out = *in
	out.Command = append([]string(nil), in.Command...)
	out.Args = append([]string(nil), in.Args...)
}
func (in *EngineSpec) DeepCopy() *EngineSpec {
	if in == nil {
		return nil
	}
	out := new(EngineSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *InferenceServiceSpec) DeepCopyInto(out *InferenceServiceSpec) {
	*out = *in
	out.ModelRef = in.ModelRef.DeepCopy()
	out.Engine = in.Engine.DeepCopy()
	out.Resource = *in.Resource.DeepCopy()
	if in.Endpoint != nil {
		out.Endpoint = new(EndpointSpec)
		*out.Endpoint = *in.Endpoint
	}
}
func (in *InferenceServiceSpec) DeepCopy() *InferenceServiceSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *RuntimeStatus) DeepCopyInto(out *RuntimeStatus) {
	*out = *in
	if in.ObservedAt != nil {
		out.ObservedAt = in.ObservedAt.DeepCopy()
	}
	if in.StaleAfter != nil {
		out.StaleAfter = in.StaleAfter.DeepCopy()
	}
}
func (in *RuntimeStatus) DeepCopy() *RuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(RuntimeStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *PublicationStatus) DeepCopyInto(out *PublicationStatus) {
	*out = *in
	if in.ObservedAt != nil {
		out.ObservedAt = in.ObservedAt.DeepCopy()
	}
}
func (in *PublicationStatus) DeepCopy() *PublicationStatus {
	if in == nil {
		return nil
	}
	out := new(PublicationStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *InvocationStatus) DeepCopyInto(out *InvocationStatus) {
	*out = *in
	if in.ObservedAt != nil {
		out.ObservedAt = in.ObservedAt.DeepCopy()
	}
}
func (in *InvocationStatus) DeepCopy() *InvocationStatus {
	if in == nil {
		return nil
	}
	out := new(InvocationStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *OperationStatus) DeepCopyInto(out *OperationStatus) { *out = *in }
func (in *OperationStatus) DeepCopy() *OperationStatus {
	if in == nil {
		return nil
	}
	out := new(OperationStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *InferenceServiceStatus) DeepCopyInto(out *InferenceServiceStatus) {
	*out = *in
	if in.ObservedAt != nil {
		out.ObservedAt = in.ObservedAt.DeepCopy()
	}
	out.Runtime = in.Runtime.DeepCopy()
	out.Publication = in.Publication.DeepCopy()
	out.Invocation = in.Invocation.DeepCopy()
	out.Operation = in.Operation.DeepCopy()
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for i := range in.Conditions {
			in.Conditions[i].DeepCopyInto(&out.Conditions[i])
		}
	}
}
func (in *InferenceServiceStatus) DeepCopy() *InferenceServiceStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceStatus)
	in.DeepCopyInto(out)
	return out
}
func (in *InferenceService) DeepCopyInto(out *InferenceService) {
	*out = *in
	out.ObjectMeta = *in.ObjectMeta.DeepCopy()
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *InferenceService) DeepCopy() *InferenceService {
	if in == nil {
		return nil
	}
	out := new(InferenceService)
	in.DeepCopyInto(out)
	return out
}
func (in *InferenceService) DeepCopyObject() runtime.Object { return in.DeepCopy() }
func (in *InferenceServiceList) DeepCopyInto(out *InferenceServiceList) {
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]InferenceService, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *InferenceServiceList) DeepCopy() *InferenceServiceList {
	if in == nil {
		return nil
	}
	out := new(InferenceServiceList)
	in.DeepCopyInto(out)
	return out
}
func (in *InferenceServiceList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
