// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference/v1/inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeMode int32

const (
	RuntimeMode_RUNTIME_MODE_UNSPECIFIED       RuntimeMode = 0
	RuntimeMode_RUNTIME_MODE_DEPLOYMENT        RuntimeMode = 1
	RuntimeMode_RUNTIME_MODE_LEADER_WORKER_SET RuntimeMode = 2
)

// Enum value maps for RuntimeMode.
var (
	RuntimeMode_name = map[int32]string{
		0: "RUNTIME_MODE_UNSPECIFIED",
		1: "RUNTIME_MODE_DEPLOYMENT",
		2: "RUNTIME_MODE_LEADER_WORKER_SET",
	}
	RuntimeMode_value = map[string]int32{
		"RUNTIME_MODE_UNSPECIFIED":       0,
		"RUNTIME_MODE_DEPLOYMENT":        1,
		"RUNTIME_MODE_LEADER_WORKER_SET": 2,
	}
)

func (x RuntimeMode) Enum() *RuntimeMode {
	p := new(RuntimeMode)
	*p = x
	return p
}

func (x RuntimeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_v1_inference_proto_enumTypes[0].Descriptor()
}

func (RuntimeMode) Type() protoreflect.EnumType {
	return &file_inference_v1_inference_proto_enumTypes[0]
}

func (x RuntimeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeMode.Descriptor instead.
func (RuntimeMode) EnumDescriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      map[string]string      `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limits        map[string]string      `protobuf:"bytes,2,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceSpec) GetRequests() map[string]string {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceSpec) GetLimits() map[string]string {
	if x != nil {
		return x.Limits
	}
	return nil
}

type RuntimeSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Mode  RuntimeMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=inference.v1.RuntimeMode" json:"mode,omitempty"`
	// Number of workers in each LeaderWorkerSet group. It is ignored for a
	// Deployment and must be positive for the distributed mode.
	WorkerReplicas int32         `protobuf:"varint,2,opt,name=worker_replicas,json=workerReplicas,proto3" json:"worker_replicas,omitempty"`
	Endpoint       *EndpointSpec `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RuntimeSpec) Reset() {
	*x = RuntimeSpec{}
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSpec) ProtoMessage() {}

func (x *RuntimeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSpec.ProtoReflect.Descriptor instead.
func (*RuntimeSpec) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *RuntimeSpec) GetMode() RuntimeMode {
	if x != nil {
		return x.Mode
	}
	return RuntimeMode_RUNTIME_MODE_UNSPECIFIED
}

func (x *RuntimeSpec) GetWorkerReplicas() int32 {
	if x != nil {
		return x.WorkerReplicas
	}
	return 0
}

func (x *RuntimeSpec) GetEndpoint() *EndpointSpec {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

// EndpointSpec describes the optional Kubernetes Service exposed for this
// runtime. Ports are explicit; an omitted endpoint means no Service is owned.
type EndpointSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerPort int32                  `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	ServicePort   int32                  `protobuf:"varint,2,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	TargetPort    string                 `protobuf:"bytes,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointSpec) Reset() {
	*x = EndpointSpec{}
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointSpec) ProtoMessage() {}

func (x *EndpointSpec) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointSpec.ProtoReflect.Descriptor instead.
func (*EndpointSpec) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointSpec) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *EndpointSpec) GetServicePort() int32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *EndpointSpec) GetTargetPort() string {
	if x != nil {
		return x.TargetPort
	}
	return ""
}

func (x *EndpointSpec) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ModelArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelArtifact) Reset() {
	*x = ModelArtifact{}
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelArtifact) ProtoMessage() {}

func (x *ModelArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelArtifact.ProtoReflect.Descriptor instead.
func (*ModelArtifact) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ModelArtifact) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelArtifact) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ModelArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type EngineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,3,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EngineSpec) Reset() {
	*x = EngineSpec{}
	mi := &file_inference_v1_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineSpec) ProtoMessage() {}

func (x *EngineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineSpec.ProtoReflect.Descriptor instead.
func (*EngineSpec) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{4}
}

func (x *EngineSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EngineSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *EngineSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *EngineSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type InferenceService struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DesiredState     string                 `protobuf:"bytes,3,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	Generation       int64                  `protobuf:"varint,4,opt,name=generation,proto3" json:"generation,omitempty"`
	ModelVersionId   string                 `protobuf:"bytes,5,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	Resource         *ResourceSpec          `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	Replicas         int32                  `protobuf:"varint,7,opt,name=replicas,proto3" json:"replicas,omitempty"`
	RuntimePhase     string                 `protobuf:"bytes,8,opt,name=runtime_phase,json=runtimePhase,proto3" json:"runtime_phase,omitempty"`
	PublicationPhase string                 `protobuf:"bytes,9,opt,name=publication_phase,json=publicationPhase,proto3" json:"publication_phase,omitempty"`
	InvocationHealth string                 `protobuf:"bytes,10,opt,name=invocation_health,json=invocationHealth,proto3" json:"invocation_health,omitempty"`
	ObservedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	Runtime          *RuntimeSpec           `protobuf:"bytes,12,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ModelArtifact    *ModelArtifact         `protobuf:"bytes,13,opt,name=model_artifact,json=modelArtifact,proto3" json:"model_artifact,omitempty"`
	Engine           *EngineSpec            `protobuf:"bytes,14,opt,name=engine,proto3" json:"engine,omitempty"`
	// Latest generation whose runtime observation was durably committed.
	// This is distinct from desired generation and readiness facts.
	AppliedGeneration int64  `protobuf:"varint,15,opt,name=applied_generation,json=appliedGeneration,proto3" json:"applied_generation,omitempty"`
	ServedModelName   string `protobuf:"bytes,16,opt,name=served_model_name,json=servedModelName,proto3" json:"served_model_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InferenceService) Reset() {
	*x = InferenceService{}
	mi := &file_inference_v1_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferenceService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferenceService) ProtoMessage() {}

func (x *InferenceService) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferenceService.ProtoReflect.Descriptor instead.
func (*InferenceService) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{5}
}

func (x *InferenceService) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InferenceService) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InferenceService) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *InferenceService) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *InferenceService) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *InferenceService) GetResource() *ResourceSpec {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *InferenceService) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *InferenceService) GetRuntimePhase() string {
	if x != nil {
		return x.RuntimePhase
	}
	return ""
}

func (x *InferenceService) GetPublicationPhase() string {
	if x != nil {
		return x.PublicationPhase
	}
	return ""
}

func (x *InferenceService) GetInvocationHealth() string {
	if x != nil {
		return x.InvocationHealth
	}
	return ""
}

func (x *InferenceService) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *InferenceService) GetRuntime() *RuntimeSpec {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *InferenceService) GetModelArtifact() *ModelArtifact {
	if x != nil {
		return x.ModelArtifact
	}
	return nil
}

func (x *InferenceService) GetEngine() *EngineSpec {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *InferenceService) GetAppliedGeneration() int64 {
	if x != nil {
		return x.AppliedGeneration
	}
	return 0
}

func (x *InferenceService) GetServedModelName() string {
	if x != nil {
		return x.ServedModelName
	}
	return ""
}

type Operation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId        string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Kind             string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Phase            string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Step             string                 `protobuf:"bytes,5,opt,name=step,proto3" json:"step,omitempty"`
	TargetGeneration int64                  `protobuf:"varint,6,opt,name=target_generation,json=targetGeneration,proto3" json:"target_generation,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_inference_v1_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{6}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Operation) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Operation) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Operation) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *Operation) GetTargetGeneration() int64 {
	if x != nil {
		return x.TargetGeneration
	}
	return 0
}

func (x *Operation) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Operation) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Operation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type CreateInferenceServiceRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestId       string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ModelVersionId  string                 `protobuf:"bytes,3,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	Resource        *ResourceSpec          `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Replicas        int32                  `protobuf:"varint,5,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Runtime         *RuntimeSpec           `protobuf:"bytes,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ModelArtifact   *ModelArtifact         `protobuf:"bytes,7,opt,name=model_artifact,json=modelArtifact,proto3" json:"model_artifact,omitempty"`
	Engine          *EngineSpec            `protobuf:"bytes,8,opt,name=engine,proto3" json:"engine,omitempty"`
	ServedModelName string                 `protobuf:"bytes,9,opt,name=served_model_name,json=servedModelName,proto3" json:"served_model_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateInferenceServiceRequest) Reset() {
	*x = CreateInferenceServiceRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInferenceServiceRequest) ProtoMessage() {}

func (x *CreateInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{7}
}

func (x *CreateInferenceServiceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *CreateInferenceServiceRequest) GetResource() *ResourceSpec {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CreateInferenceServiceRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *CreateInferenceServiceRequest) GetRuntime() *RuntimeSpec {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *CreateInferenceServiceRequest) GetModelArtifact() *ModelArtifact {
	if x != nil {
		return x.ModelArtifact
	}
	return nil
}

func (x *CreateInferenceServiceRequest) GetEngine() *EngineSpec {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *CreateInferenceServiceRequest) GetServedModelName() string {
	if x != nil {
		return x.ServedModelName
	}
	return ""
}

type UpdateInferenceServiceRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResourceId         string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ExpectedGeneration int64                  `protobuf:"varint,3,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	UpdateMask         *fieldmaskpb.FieldMask `protobuf:"bytes,4,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Resource           *ResourceSpec          `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Replicas           int32                  `protobuf:"varint,6,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Runtime            *RuntimeSpec           `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ModelArtifact      *ModelArtifact         `protobuf:"bytes,8,opt,name=model_artifact,json=modelArtifact,proto3" json:"model_artifact,omitempty"`
	Engine             *EngineSpec            `protobuf:"bytes,9,opt,name=engine,proto3" json:"engine,omitempty"`
	ServedModelName    string                 `protobuf:"bytes,10,opt,name=served_model_name,json=servedModelName,proto3" json:"served_model_name,omitempty"`
	ModelVersionId     string                 `protobuf:"bytes,11,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateInferenceServiceRequest) Reset() {
	*x = UpdateInferenceServiceRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInferenceServiceRequest) ProtoMessage() {}

func (x *UpdateInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateInferenceServiceRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UpdateInferenceServiceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UpdateInferenceServiceRequest) GetExpectedGeneration() int64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

func (x *UpdateInferenceServiceRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateInferenceServiceRequest) GetResource() *ResourceSpec {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *UpdateInferenceServiceRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *UpdateInferenceServiceRequest) GetRuntime() *RuntimeSpec {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *UpdateInferenceServiceRequest) GetModelArtifact() *ModelArtifact {
	if x != nil {
		return x.ModelArtifact
	}
	return nil
}

func (x *UpdateInferenceServiceRequest) GetEngine() *EngineSpec {
	if x != nil {
		return x.Engine
	}
	return nil
}

func (x *UpdateInferenceServiceRequest) GetServedModelName() string {
	if x != nil {
		return x.ServedModelName
	}
	return ""
}

func (x *UpdateInferenceServiceRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

type ServiceCommandRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ResourceId         string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ExpectedGeneration int64                  `protobuf:"varint,3,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceCommandRequest) Reset() {
	*x = ServiceCommandRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCommandRequest) ProtoMessage() {}

func (x *ServiceCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCommandRequest.ProtoReflect.Descriptor instead.
func (*ServiceCommandRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{9}
}

func (x *ServiceCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceCommandRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ServiceCommandRequest) GetExpectedGeneration() int64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

type GetInferenceServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInferenceServiceRequest) Reset() {
	*x = GetInferenceServiceRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInferenceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInferenceServiceRequest) ProtoMessage() {}

func (x *GetInferenceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInferenceServiceRequest.ProtoReflect.Descriptor instead.
func (*GetInferenceServiceRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{10}
}

func (x *GetInferenceServiceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListInferenceServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceServicesRequest) Reset() {
	*x = ListInferenceServicesRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceServicesRequest) ProtoMessage() {}

func (x *ListInferenceServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceServicesRequest.ProtoReflect.Descriptor instead.
func (*ListInferenceServicesRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{11}
}

func (x *ListInferenceServicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInferenceServicesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListInferenceServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*InferenceService    `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInferenceServicesResponse) Reset() {
	*x = ListInferenceServicesResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInferenceServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInferenceServicesResponse) ProtoMessage() {}

func (x *ListInferenceServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInferenceServicesResponse.ProtoReflect.Descriptor instead.
func (*ListInferenceServicesResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{12}
}

func (x *ListInferenceServicesResponse) GetServices() []*InferenceService {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *ListInferenceServicesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *InferenceService      `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{13}
}

func (x *OperationResponse) GetResource() *InferenceService {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *OperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{14}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ListOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsRequest) Reset() {
	*x = ListOperationsRequest{}
	mi := &file_inference_v1_inference_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsRequest) ProtoMessage() {}

func (x *ListOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsRequest.ProtoReflect.Descriptor instead.
func (*ListOperationsRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{15}
}

func (x *ListOperationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOperationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListOperationsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ListOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*Operation           `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOperationsResponse) Reset() {
	*x = ListOperationsResponse{}
	mi := &file_inference_v1_inference_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOperationsResponse) ProtoMessage() {}

func (x *ListOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_inference_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOperationsResponse.ProtoReflect.Descriptor instead.
func (*ListOperationsResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_inference_proto_rawDescGZIP(), []int{16}
}

func (x *ListOperationsResponse) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ListOperationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_inference_v1_inference_proto protoreflect.FileDescriptor

const file_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"\x1cinference/v1/inference.proto\x12\finference.v1\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8c\x02\n" +
	"\fResourceSpec\x12D\n" +
	"\brequests\x18\x01 \x03(\v2(.inference.v1.ResourceSpec.RequestsEntryR\brequests\x12>\n" +
	"\x06limits\x18\x02 \x03(\v2&.inference.v1.ResourceSpec.LimitsEntryR\x06limits\x1a;\n" +
	"\rRequestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\vRuntimeSpec\x12-\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x19.inference.v1.RuntimeModeR\x04mode\x12'\n" +
	"\x0fworker_replicas\x18\x02 \x01(\x05R\x0eworkerReplicas\x126\n" +
	"\bendpoint\x18\x03 \x01(\v2\x1a.inference.v1.EndpointSpecR\bendpoint\"\x95\x01\n" +
	"\fEndpointSpec\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\x05R\rcontainerPort\x12!\n" +
	"\fservice_port\x18\x02 \x01(\x05R\vservicePort\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\tR\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\"a\n" +
	"\rModelArtifact\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\"d\n" +
	"\n" +
	"EngineSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x03 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\"\xbb\x05\n" +
	"\x10InferenceService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rdesired_state\x18\x03 \x01(\tR\fdesiredState\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\x03R\n" +
	"generation\x12(\n" +
	"\x10model_version_id\x18\x05 \x01(\tR\x0emodelVersionId\x126\n" +
	"\bresource\x18\x06 \x01(\v2\x1a.inference.v1.ResourceSpecR\bresource\x12\x1a\n" +
	"\breplicas\x18\a \x01(\x05R\breplicas\x12#\n" +
	"\rruntime_phase\x18\b \x01(\tR\fruntimePhase\x12+\n" +
	"\x11publication_phase\x18\t \x01(\tR\x10publicationPhase\x12+\n" +
	"\x11invocation_health\x18\n" +
	" \x01(\tR\x10invocationHealth\x12;\n" +
	"\vobserved_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x123\n" +
	"\aruntime\x18\f \x01(\v2\x19.inference.v1.RuntimeSpecR\aruntime\x12B\n" +
	"\x0emodel_artifact\x18\r \x01(\v2\x1b.inference.v1.ModelArtifactR\rmodelArtifact\x120\n" +
	"\x06engine\x18\x0e \x01(\v2\x18.inference.v1.EngineSpecR\x06engine\x12-\n" +
	"\x12applied_generation\x18\x0f \x01(\x03R\x11appliedGeneration\x12*\n" +
	"\x11served_model_name\x18\x10 \x01(\tR\x0fservedModelName\"\xe3\x02\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x12\n" +
	"\x04step\x18\x05 \x01(\tR\x04step\x12+\n" +
	"\x11target_generation\x18\x06 \x01(\x03R\x10targetGeneration\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"\xa7\x03\n" +
	"\x1dCreateInferenceServiceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x10model_version_id\x18\x03 \x01(\tR\x0emodelVersionId\x126\n" +
	"\bresource\x18\x04 \x01(\v2\x1a.inference.v1.ResourceSpecR\bresource\x12\x1a\n" +
	"\breplicas\x18\x05 \x01(\x05R\breplicas\x123\n" +
	"\aruntime\x18\x06 \x01(\v2\x19.inference.v1.RuntimeSpecR\aruntime\x12B\n" +
	"\x0emodel_artifact\x18\a \x01(\v2\x1b.inference.v1.ModelArtifactR\rmodelArtifact\x120\n" +
	"\x06engine\x18\b \x01(\v2\x18.inference.v1.EngineSpecR\x06engine\x12*\n" +
	"\x11served_model_name\x18\t \x01(\tR\x0fservedModelName\"\xa2\x04\n" +
	"\x1dUpdateInferenceServiceRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12/\n" +
	"\x13expected_generation\x18\x03 \x01(\x03R\x12expectedGeneration\x12;\n" +
	"\vupdate_mask\x18\x04 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x126\n" +
	"\bresource\x18\x05 \x01(\v2\x1a.inference.v1.ResourceSpecR\bresource\x12\x1a\n" +
	"\breplicas\x18\x06 \x01(\x05R\breplicas\x123\n" +
	"\aruntime\x18\a \x01(\v2\x19.inference.v1.RuntimeSpecR\aruntime\x12B\n" +
	"\x0emodel_artifact\x18\b \x01(\v2\x1b.inference.v1.ModelArtifactR\rmodelArtifact\x120\n" +
	"\x06engine\x18\t \x01(\v2\x18.inference.v1.EngineSpecR\x06engine\x12*\n" +
	"\x11served_model_name\x18\n" +
	" \x01(\tR\x0fservedModelName\x12(\n" +
	"\x10model_version_id\x18\v \x01(\tR\x0emodelVersionId\"\x88\x01\n" +
	"\x15ServiceCommandRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12/\n" +
	"\x13expected_generation\x18\x03 \x01(\x03R\x12expectedGeneration\"=\n" +
	"\x1aGetInferenceServiceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"Z\n" +
	"\x1cListInferenceServicesRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x1dListInferenceServicesResponse\x12:\n" +
	"\bservices\x18\x01 \x03(\v2\x1e.inference.v1.InferenceServiceR\bservices\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x86\x01\n" +
	"\x11OperationResponse\x12:\n" +
	"\bresource\x18\x01 \x01(\v2\x1e.inference.v1.InferenceServiceR\bresource\x125\n" +
	"\toperation\x18\x02 \x01(\v2\x17.inference.v1.OperationR\toperation\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"t\n" +
	"\x15ListOperationsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"y\n" +
	"\x16ListOperationsResponse\x127\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x17.inference.v1.OperationR\n" +
	"operations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken*l\n" +
	"\vRuntimeMode\x12\x1c\n" +
	"\x18RUNTIME_MODE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RUNTIME_MODE_DEPLOYMENT\x10\x01\x12\"\n" +
	"\x1eRUNTIME_MODE_LEADER_WORKER_SET\x10\x022\xe3\a\n" +
	"\x17InferenceServiceManager\x12f\n" +
	"\x16CreateInferenceService\x12+.inference.v1.CreateInferenceServiceRequest\x1a\x1f.inference.v1.OperationResponse\x12_\n" +
	"\x13GetInferenceService\x12(.inference.v1.GetInferenceServiceRequest\x1a\x1e.inference.v1.InferenceService\x12p\n" +
	"\x15ListInferenceServices\x12*.inference.v1.ListInferenceServicesRequest\x1a+.inference.v1.ListInferenceServicesResponse\x12f\n" +
	"\x16UpdateInferenceService\x12+.inference.v1.UpdateInferenceServiceRequest\x1a\x1f.inference.v1.OperationResponse\x12]\n" +
	"\x15StartInferenceService\x12#.inference.v1.ServiceCommandRequest\x1a\x1f.inference.v1.OperationResponse\x12\\\n" +
	"\x14StopInferenceService\x12#.inference.v1.ServiceCommandRequest\x1a\x1f.inference.v1.OperationResponse\x12_\n" +
	"\x17RestartInferenceService\x12#.inference.v1.ServiceCommandRequest\x1a\x1f.inference.v1.OperationResponse\x12^\n" +
	"\x16DeleteInferenceService\x12#.inference.v1.ServiceCommandRequest\x1a\x1f.inference.v1.OperationResponse\x12J\n" +
	"\fGetOperation\x12!.inference.v1.GetOperationRequest\x1a\x17.inference.v1.Operation\x12[\n" +
	"\x0eListOperations\x12#.inference.v1.ListOperationsRequest\x1a$.inference.v1.ListOperationsResponseBMZKgithub.com/zhangzhe-ctrl/ani-inference-service/api/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_v1_inference_proto_rawDescOnce sync.Once
	file_inference_v1_inference_proto_rawDescData []byte
)

func file_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)))
	})
	return file_inference_v1_inference_proto_rawDescData
}

var file_inference_v1_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_inference_v1_inference_proto_goTypes = []any{
	(RuntimeMode)(0),                      // 0: inference.v1.RuntimeMode
	(*ResourceSpec)(nil),                  // 1: inference.v1.ResourceSpec
	(*RuntimeSpec)(nil),                   // 2: inference.v1.RuntimeSpec
	(*EndpointSpec)(nil),                  // 3: inference.v1.EndpointSpec
	(*ModelArtifact)(nil),                 // 4: inference.v1.ModelArtifact
	(*EngineSpec)(nil),                    // 5: inference.v1.EngineSpec
	(*InferenceService)(nil),              // 6: inference.v1.InferenceService
	(*Operation)(nil),                     // 7: inference.v1.Operation
	(*CreateInferenceServiceRequest)(nil), // 8: inference.v1.CreateInferenceServiceRequest
	(*UpdateInferenceServiceRequest)(nil), // 9: inference.v1.UpdateInferenceServiceRequest
	(*ServiceCommandRequest)(nil),         // 10: inference.v1.ServiceCommandRequest
	(*GetInferenceServiceRequest)(nil),    // 11: inference.v1.GetInferenceServiceRequest
	(*ListInferenceServicesRequest)(nil),  // 12: inference.v1.ListInferenceServicesRequest
	(*ListInferenceServicesResponse)(nil), // 13: inference.v1.ListInferenceServicesResponse
	(*OperationResponse)(nil),             // 14: inference.v1.OperationResponse
	(*GetOperationRequest)(nil),           // 15: inference.v1.GetOperationRequest
	(*ListOperationsRequest)(nil),         // 16: inference.v1.ListOperationsRequest
	(*ListOperationsResponse)(nil),        // 17: inference.v1.ListOperationsResponse
	nil,                                   // 18: inference.v1.ResourceSpec.RequestsEntry
	nil,                                   // 19: inference.v1.ResourceSpec.LimitsEntry
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),         // 21: google.protobuf.FieldMask
}
var file_inference_v1_inference_proto_depIdxs = []int32{
	18, // 0: inference.v1.ResourceSpec.requests:type_name -> inference.v1.ResourceSpec.RequestsEntry
	19, // 1: inference.v1.ResourceSpec.limits:type_name -> inference.v1.ResourceSpec.LimitsEntry
	0,  // 2: inference.v1.RuntimeSpec.mode:type_name -> inference.v1.RuntimeMode
	3,  // 3: inference.v1.RuntimeSpec.endpoint:type_name -> inference.v1.EndpointSpec
	1,  // 4: inference.v1.InferenceService.resource:type_name -> inference.v1.ResourceSpec
	20, // 5: inference.v1.InferenceService.observed_at:type_name -> google.protobuf.Timestamp
	2,  // 6: inference.v1.InferenceService.runtime:type_name -> inference.v1.RuntimeSpec
	4,  // 7: inference.v1.InferenceService.model_artifact:type_name -> inference.v1.ModelArtifact
	5,  // 8: inference.v1.InferenceService.engine:type_name -> inference.v1.EngineSpec
	20, // 9: inference.v1.Operation.created_at:type_name -> google.protobuf.Timestamp
	20, // 10: inference.v1.Operation.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 11: inference.v1.CreateInferenceServiceRequest.resource:type_name -> inference.v1.ResourceSpec
	2,  // 12: inference.v1.CreateInferenceServiceRequest.runtime:type_name -> inference.v1.RuntimeSpec
	4,  // 13: inference.v1.CreateInferenceServiceRequest.model_artifact:type_name -> inference.v1.ModelArtifact
	5,  // 14: inference.v1.CreateInferenceServiceRequest.engine:type_name -> inference.v1.EngineSpec
	21, // 15: inference.v1.UpdateInferenceServiceRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 16: inference.v1.UpdateInferenceServiceRequest.resource:type_name -> inference.v1.ResourceSpec
	2,  // 17: inference.v1.UpdateInferenceServiceRequest.runtime:type_name -> inference.v1.RuntimeSpec
	4,  // 18: inference.v1.UpdateInferenceServiceRequest.model_artifact:type_name -> inference.v1.ModelArtifact
	5,  // 19: inference.v1.UpdateInferenceServiceRequest.engine:type_name -> inference.v1.EngineSpec
	6,  // 20: inference.v1.ListInferenceServicesResponse.services:type_name -> inference.v1.InferenceService
	6,  // 21: inference.v1.OperationResponse.resource:type_name -> inference.v1.InferenceService
	7,  // 22: inference.v1.OperationResponse.operation:type_name -> inference.v1.Operation
	7,  // 23: inference.v1.ListOperationsResponse.operations:type_name -> inference.v1.Operation
	8,  // 24: inference.v1.InferenceServiceManager.CreateInferenceService:input_type -> inference.v1.CreateInferenceServiceRequest
	11, // 25: inference.v1.InferenceServiceManager.GetInferenceService:input_type -> inference.v1.GetInferenceServiceRequest
	12, // 26: inference.v1.InferenceServiceManager.ListInferenceServices:input_type -> inference.v1.ListInferenceServicesRequest
	9,  // 27: inference.v1.InferenceServiceManager.UpdateInferenceService:input_type -> inference.v1.UpdateInferenceServiceRequest
	10, // 28: inference.v1.InferenceServiceManager.StartInferenceService:input_type -> inference.v1.ServiceCommandRequest
	10, // 29: inference.v1.InferenceServiceManager.StopInferenceService:input_type -> inference.v1.ServiceCommandRequest
	10, // 30: inference.v1.InferenceServiceManager.RestartInferenceService:input_type -> inference.v1.ServiceCommandRequest
	10, // 31: inference.v1.InferenceServiceManager.DeleteInferenceService:input_type -> inference.v1.ServiceCommandRequest
	15, // 32: inference.v1.InferenceServiceManager.GetOperation:input_type -> inference.v1.GetOperationRequest
	16, // 33: inference.v1.InferenceServiceManager.ListOperations:input_type -> inference.v1.ListOperationsRequest
	14, // 34: inference.v1.InferenceServiceManager.CreateInferenceService:output_type -> inference.v1.OperationResponse
	6,  // 35: inference.v1.InferenceServiceManager.GetInferenceService:output_type -> inference.v1.InferenceService
	13, // 36: inference.v1.InferenceServiceManager.ListInferenceServices:output_type -> inference.v1.ListInferenceServicesResponse
	14, // 37: inference.v1.InferenceServiceManager.UpdateInferenceService:output_type -> inference.v1.OperationResponse
	14, // 38: inference.v1.InferenceServiceManager.StartInferenceService:output_type -> inference.v1.OperationResponse
	14, // 39: inference.v1.InferenceServiceManager.StopInferenceService:output_type -> inference.v1.OperationResponse
	14, // 40: inference.v1.InferenceServiceManager.RestartInferenceService:output_type -> inference.v1.OperationResponse
	14, // 41: inference.v1.InferenceServiceManager.DeleteInferenceService:output_type -> inference.v1.OperationResponse
	7,  // 42: inference.v1.InferenceServiceManager.GetOperation:output_type -> inference.v1.Operation
	17, // 43: inference.v1.InferenceServiceManager.ListOperations:output_type -> inference.v1.ListOperationsResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_inference_v1_inference_proto_init() }
func file_inference_v1_inference_proto_init() {
	if File_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_inference_proto_rawDesc), len(file_inference_v1_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_inference_v1_inference_proto_depIdxs,
		EnumInfos:         file_inference_v1_inference_proto_enumTypes,
		MessageInfos:      file_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_inference_v1_inference_proto = out.File
	file_inference_v1_inference_proto_goTypes = nil
	file_inference_v1_inference_proto_depIdxs = nil
}
