// Code generated by protoc-gen-go-grpc-compatible template. DO NOT EDIT.
package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

type InferenceServiceManagerClient interface {
	CreateInferenceService(context.Context, *CreateInferenceServiceRequest, ...grpc.CallOption) (*OperationResponse, error)
	GetInferenceService(context.Context, *GetInferenceServiceRequest, ...grpc.CallOption) (*InferenceService, error)
	ListInferenceServices(context.Context, *ListInferenceServicesRequest, ...grpc.CallOption) (*ListInferenceServicesResponse, error)
	UpdateInferenceService(context.Context, *UpdateInferenceServiceRequest, ...grpc.CallOption) (*OperationResponse, error)
	StartInferenceService(context.Context, *ServiceCommandRequest, ...grpc.CallOption) (*OperationResponse, error)
	StopInferenceService(context.Context, *ServiceCommandRequest, ...grpc.CallOption) (*OperationResponse, error)
	RestartInferenceService(context.Context, *ServiceCommandRequest, ...grpc.CallOption) (*OperationResponse, error)
	DeleteInferenceService(context.Context, *ServiceCommandRequest, ...grpc.CallOption) (*OperationResponse, error)
	GetOperation(context.Context, *GetOperationRequest, ...grpc.CallOption) (*Operation, error)
}

type inferenceServiceManagerClient struct{ cc grpc.ClientConnInterface }

func NewInferenceServiceManagerClient(cc grpc.ClientConnInterface) InferenceServiceManagerClient {
	return &inferenceServiceManagerClient{cc}
}
func (c *inferenceServiceManagerClient) invoke(ctx context.Context, method string, in, out any, opts ...grpc.CallOption) error {
	return c.cc.Invoke(ctx, method, in, out, opts...)
}
func (c *inferenceServiceManagerClient) CreateInferenceService(ctx context.Context, in *CreateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/CreateInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) GetInferenceService(ctx context.Context, in *GetInferenceServiceRequest, opts ...grpc.CallOption) (*InferenceService, error) {
	out := new(InferenceService)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/GetInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) ListInferenceServices(ctx context.Context, in *ListInferenceServicesRequest, opts ...grpc.CallOption) (*ListInferenceServicesResponse, error) {
	out := new(ListInferenceServicesResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/ListInferenceServices", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) UpdateInferenceService(ctx context.Context, in *UpdateInferenceServiceRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/UpdateInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) StartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/StartInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) StopInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/StopInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) RestartInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/RestartInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) DeleteInferenceService(ctx context.Context, in *ServiceCommandRequest, opts ...grpc.CallOption) (*OperationResponse, error) {
	out := new(OperationResponse)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/DeleteInferenceService", in, out, opts...)
	return out, err
}
func (c *inferenceServiceManagerClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	out := new(Operation)
	err := c.invoke(ctx, "/inference.v1.InferenceServiceManager/GetOperation", in, out, opts...)
	return out, err
}

type InferenceServiceManagerServer interface {
	CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*OperationResponse, error)
	GetInferenceService(context.Context, *GetInferenceServiceRequest) (*InferenceService, error)
	ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error)
	UpdateInferenceService(context.Context, *UpdateInferenceServiceRequest) (*OperationResponse, error)
	StartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	StopInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	RestartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	DeleteInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error)
	GetOperation(context.Context, *GetOperationRequest) (*Operation, error)
	mustEmbedUnimplementedInferenceServiceManagerServer()
}
type UnimplementedInferenceServiceManagerServer struct{}

func (UnimplementedInferenceServiceManagerServer) mustEmbedUnimplementedInferenceServiceManagerServer() {
}
func (UnimplementedInferenceServiceManagerServer) CreateInferenceService(context.Context, *CreateInferenceServiceRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) GetInferenceService(context.Context, *GetInferenceServiceRequest) (*InferenceService, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) ListInferenceServices(context.Context, *ListInferenceServicesRequest) (*ListInferenceServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInferenceServices not implemented")
}
func (UnimplementedInferenceServiceManagerServer) UpdateInferenceService(context.Context, *UpdateInferenceServiceRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) StartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) StopInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) RestartInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) DeleteInferenceService(context.Context, *ServiceCommandRequest) (*OperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteInferenceService not implemented")
}
func (UnimplementedInferenceServiceManagerServer) GetOperation(context.Context, *GetOperationRequest) (*Operation, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}

func RegisterInferenceServiceManagerServer(s grpc.ServiceRegistrar, srv InferenceServiceManagerServer) {
	s.RegisterService(&InferenceServiceManager_ServiceDesc, srv)
}
func unary[T any, R any](srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor, method func(context.Context, T) (R, error), in T, name string) (R, error) {
	var zero R
	if err := dec(in); err != nil {
		return zero, err
	}
	if interceptor == nil {
		return method(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: name}
	handler := func(ctx context.Context, req any) (any, error) { return method(ctx, req.(T)) }
	out, err := interceptor(ctx, in, info, handler)
	if err != nil {
		return zero, err
	}
	return out.(R), nil
}

// The handlers below are intentionally explicit, matching protoc-gen-go-grpc
// output while keeping this source usable when the pinned plugin is unavailable.
func _InferenceServiceManager_CreateInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).CreateInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/CreateInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).CreateInferenceService(ctx, req.(*CreateInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_GetInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).GetInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/GetInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).GetInferenceService(ctx, req.(*GetInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_ListInferenceServices_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ListInferenceServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).ListInferenceServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/ListInferenceServices"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).ListInferenceServices(ctx, req.(*ListInferenceServicesRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_UpdateInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateInferenceServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).UpdateInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/UpdateInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).UpdateInferenceService(ctx, req.(*UpdateInferenceServiceRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_StartInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).StartInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/StartInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).StartInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_StopInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).StopInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/StopInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).StopInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_RestartInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).RestartInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/RestartInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).RestartInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_DeleteInferenceService_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ServiceCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).DeleteInferenceService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/DeleteInferenceService"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).DeleteInferenceService(ctx, req.(*ServiceCommandRequest))
	}
	return interceptor(ctx, in, info, h)
}
func _InferenceServiceManager_GetOperation_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceManagerServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/inference.v1.InferenceServiceManager/GetOperation"}
	h := func(ctx context.Context, req any) (any, error) {
		return srv.(InferenceServiceManagerServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, h)
}

var InferenceServiceManager_ServiceDesc = grpc.ServiceDesc{ServiceName: "inference.v1.InferenceServiceManager", HandlerType: (*InferenceServiceManagerServer)(nil), Methods: []grpc.MethodDesc{{MethodName: "CreateInferenceService", Handler: _InferenceServiceManager_CreateInferenceService_Handler}, {MethodName: "GetInferenceService", Handler: _InferenceServiceManager_GetInferenceService_Handler}, {MethodName: "ListInferenceServices", Handler: _InferenceServiceManager_ListInferenceServices_Handler}, {MethodName: "UpdateInferenceService", Handler: _InferenceServiceManager_UpdateInferenceService_Handler}, {MethodName: "StartInferenceService", Handler: _InferenceServiceManager_StartInferenceService_Handler}, {MethodName: "StopInferenceService", Handler: _InferenceServiceManager_StopInferenceService_Handler}, {MethodName: "RestartInferenceService", Handler: _InferenceServiceManager_RestartInferenceService_Handler}, {MethodName: "DeleteInferenceService", Handler: _InferenceServiceManager_DeleteInferenceService_Handler}, {MethodName: "GetOperation", Handler: _InferenceServiceManager_GetOperation_Handler}}, Streams: []grpc.StreamDesc{}, Metadata: "inference/v1/inference.proto"}
