// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inference.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceOperationStepCAS = `-- name: AdvanceOperationStepCAS :execrows
UPDATE inference_operations o
SET phase = $1,
    step = $2,
    error_code = $3,
    error_message = $4,
    retry_at = NULL,
    completed_at = CASE
        WHEN $1 IN ('succeeded', 'failed') THEN clock_timestamp()
        ELSE NULL
    END,
    updated_at = clock_timestamp()
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE o.tenant_id = $5
  AND o.id = $6
  AND o.target_generation = $7
  AND o.phase = $8
  AND o.step = $9
  AND (o.retry_at IS NULL OR o.retry_at <= clock_timestamp())
  AND s.tenant_id = o.tenant_id
  AND s.id = o.service_id
  AND s.current_operation_id = o.id
  AND s.desired_generation = o.target_generation
  AND w.lease_token = $10
  AND w.lease_until > clock_timestamp()
`

type AdvanceOperationStepCASParams struct {
	NextPhase        string
	NextStep         string
	ErrorCode        string
	ErrorMessage     string
	TenantID         pgtype.UUID
	OperationID      pgtype.UUID
	TargetGeneration int64
	ExpectedPhase    string
	ExpectedStep     string
	LeaseToken       pgtype.UUID
}

// A worker may advance an operation only while it is still the current
// operation for the same desired generation.  The expected phase and step
// make retries/stale workers harmless; retry_at prevents an early retry from
// racing the worker that owns the current lease.
func (q *Queries) AdvanceOperationStepCAS(ctx context.Context, arg AdvanceOperationStepCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceOperationStepCAS,
		arg.NextPhase,
		arg.NextStep,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TenantID,
		arg.OperationID,
		arg.TargetGeneration,
		arg.ExpectedPhase,
		arg.ExpectedStep,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const appendAuditEvent = `-- name: AppendAuditEvent :exec
INSERT INTO inference_audit_events
  (tenant_id, event_id, service_id, operation_id, generation, event_type, actor, request_id, before_state, after_state, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (tenant_id, event_id) DO NOTHING
`

type AppendAuditEventParams struct {
	TenantID    pgtype.UUID
	EventID     pgtype.UUID
	ServiceID   pgtype.UUID
	OperationID pgtype.UUID
	Generation  int64
	EventType   string
	Actor       string
	RequestID   string
	BeforeState []byte
	AfterState  []byte
	Payload     []byte
}

func (q *Queries) AppendAuditEvent(ctx context.Context, arg AppendAuditEventParams) error {
	_, err := q.db.Exec(ctx, appendAuditEvent,
		arg.TenantID,
		arg.EventID,
		arg.ServiceID,
		arg.OperationID,
		arg.Generation,
		arg.EventType,
		arg.Actor,
		arg.RequestID,
		arg.BeforeState,
		arg.AfterState,
		arg.Payload,
	)
	return err
}

const appendObservationEvent = `-- name: AppendObservationEvent :exec
INSERT INTO inference_observation_events
  (tenant_id, event_id, service_id, generation, source_kind,
   source_uid, source_resource_version, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type AppendObservationEventParams struct {
	TenantID              pgtype.UUID
	EventID               pgtype.UUID
	ServiceID             pgtype.UUID
	Generation            int64
	SourceKind            string
	SourceUid             string
	SourceResourceVersion string
	Payload               []byte
}

// Observation events are append-only history. The caller supplies a fresh
// event_id for every committed observation; this row is never updated.
func (q *Queries) AppendObservationEvent(ctx context.Context, arg AppendObservationEventParams) error {
	_, err := q.db.Exec(ctx, appendObservationEvent,
		arg.TenantID,
		arg.EventID,
		arg.ServiceID,
		arg.Generation,
		arg.SourceKind,
		arg.SourceUid,
		arg.SourceResourceVersion,
		arg.Payload,
	)
	return err
}

const cloneSpecGeneration = `-- name: CloneSpecGeneration :execrows
INSERT INTO inference_specs
  (tenant_id, id, service_id, generation, model_id, model_version_id,
   artifact_provider, artifact_ref, artifact_sha256, image_ref, served_model_name,
   engine_runtime, command_argv, resources, replicas, runtime_mode, worker_replicas, spec_json,
   endpoint_container_port, endpoint_service_port, endpoint_target_port, endpoint_protocol)
SELECT s.tenant_id, $1, s.service_id, $2, s.model_id, s.model_version_id,
       s.artifact_provider, s.artifact_ref, s.artifact_sha256, s.image_ref, s.served_model_name,
       s.engine_runtime, s.command_argv, s.resources, s.replicas, s.runtime_mode, s.worker_replicas, s.spec_json,
       s.endpoint_container_port, s.endpoint_service_port, s.endpoint_target_port, s.endpoint_protocol
FROM inference_specs s
WHERE s.tenant_id = $3 AND s.service_id = $4
  AND s.generation = $5
`

type CloneSpecGenerationParams struct {
	ID               pgtype.UUID
	TargetGeneration int64
	TenantID         pgtype.UUID
	ServiceID        pgtype.UUID
	SourceGeneration int64
}

func (q *Queries) CloneSpecGeneration(ctx context.Context, arg CloneSpecGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, cloneSpecGeneration,
		arg.ID,
		arg.TargetGeneration,
		arg.TenantID,
		arg.ServiceID,
		arg.SourceGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const cloneSpecWithRuntimeUpdate = `-- name: CloneSpecWithRuntimeUpdate :execrows
INSERT INTO inference_specs
  (tenant_id, id, service_id, generation, model_id, model_version_id,
   artifact_provider, artifact_ref, artifact_sha256, image_ref, served_model_name,
   engine_runtime, command_argv, resources, replicas, runtime_mode, worker_replicas, spec_json,
   endpoint_container_port, endpoint_service_port, endpoint_target_port, endpoint_protocol)
SELECT s.tenant_id, $1, s.service_id, $2, s.model_id, s.model_version_id,
       CASE WHEN $3::text <> '' THEN $3 ELSE s.artifact_provider END,
       CASE WHEN $4::text <> '' THEN $4 ELSE s.artifact_ref END,
       CASE WHEN $5::text <> '' THEN $5 ELSE s.artifact_sha256 END,
       CASE WHEN $6::text <> '' THEN $6 ELSE s.image_ref END,
       CASE WHEN $7::text <> '' THEN $7 ELSE s.served_model_name END,
       CASE WHEN $8::text <> '' THEN $8 ELSE s.engine_runtime END,
       CASE WHEN CASE WHEN jsonb_typeof($9::jsonb) = 'array' THEN jsonb_array_length($9::jsonb) ELSE 0 END > 0 THEN $9 ELSE s.command_argv END,
       $10, $11,
       $12, $13, s.spec_json,
       $14, $15, $16, $17
FROM inference_specs s
WHERE s.tenant_id = $18 AND s.service_id = $19
  AND s.generation = $20
`

type CloneSpecWithRuntimeUpdateParams struct {
	ID                    pgtype.UUID
	TargetGeneration      int64
	ArtifactProvider      string
	ArtifactRef           string
	ArtifactSha256        string
	ImageRef              string
	ServedModelName       string
	EngineRuntime         string
	CommandArgv           []byte
	Resources             []byte
	Replicas              int32
	RuntimeMode           string
	WorkerReplicas        int32
	EndpointContainerPort pgtype.Int4
	EndpointServicePort   pgtype.Int4
	EndpointTargetPort    pgtype.Text
	EndpointProtocol      pgtype.Text
	TenantID              pgtype.UUID
	ServiceID             pgtype.UUID
	SourceGeneration      int64
}

func (q *Queries) CloneSpecWithRuntimeUpdate(ctx context.Context, arg CloneSpecWithRuntimeUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, cloneSpecWithRuntimeUpdate,
		arg.ID,
		arg.TargetGeneration,
		arg.ArtifactProvider,
		arg.ArtifactRef,
		arg.ArtifactSha256,
		arg.ImageRef,
		arg.ServedModelName,
		arg.EngineRuntime,
		arg.CommandArgv,
		arg.Resources,
		arg.Replicas,
		arg.RuntimeMode,
		arg.WorkerReplicas,
		arg.EndpointContainerPort,
		arg.EndpointServicePort,
		arg.EndpointTargetPort,
		arg.EndpointProtocol,
		arg.TenantID,
		arg.ServiceID,
		arg.SourceGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRuntimeBindingCAS = `-- name: DeleteRuntimeBindingCAS :execrows
DELETE FROM inference_runtime_bindings
WHERE tenant_id = $1
  AND service_id = $2
  AND generation = $3
  AND object_kind = $4
  AND role = $5
  AND object_uid = $6
  AND resource_version = $7
`

type DeleteRuntimeBindingCASParams struct {
	TenantID        pgtype.UUID
	ServiceID       pgtype.UUID
	Generation      int64
	ObjectKind      string
	Role            string
	ObjectUid       string
	ResourceVersion string
}

func (q *Queries) DeleteRuntimeBindingCAS(ctx context.Context, arg DeleteRuntimeBindingCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRuntimeBindingCAS,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.ObjectKind,
		arg.Role,
		arg.ObjectUid,
		arg.ResourceVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureResourceWork = `-- name: EnsureResourceWork :exec
INSERT INTO inference_resource_work (tenant_id, service_id, dirty_version, acknowledged_version)
VALUES ($1, $2, $3, 0)
ON CONFLICT (tenant_id, service_id) DO NOTHING
`

type EnsureResourceWorkParams struct {
	TenantID     pgtype.UUID
	ServiceID    pgtype.UUID
	DirtyVersion int64
}

// Startup/periodic repair must not turn a complete service scan into a
// notification storm. Existing rows retain their durable sequence and
// schedule; only a missing row is recreated and made immediately due.
func (q *Queries) EnsureResourceWork(ctx context.Context, arg EnsureResourceWorkParams) error {
	_, err := q.db.Exec(ctx, ensureResourceWork, arg.TenantID, arg.ServiceID, arg.DirtyVersion)
	return err
}

const getActiveQuotaReservation = `-- name: GetActiveQuotaReservation :one
SELECT tenant_id, service_id, operation_id, generation, reservation_id,
       requested_resources, state, last_error_code, created_at, updated_at
FROM inference_quota_reservations
WHERE tenant_id = $1 AND service_id = $2 AND generation <= $3
  AND state IN ('pending', 'reserved', 'confirmed', 'release_pending')
ORDER BY generation DESC, updated_at DESC
LIMIT 1
`

type GetActiveQuotaReservationParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetActiveQuotaReservation(ctx context.Context, arg GetActiveQuotaReservationParams) (InferenceQuotaReservation, error) {
	row := q.db.QueryRow(ctx, getActiveQuotaReservation, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferenceQuotaReservation
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.OperationID,
		&i.Generation,
		&i.ReservationID,
		&i.RequestedResources,
		&i.State,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT tenant_id, method, idempotency_key, payload_hash, operation_id, created_at, expires_at
FROM inference_idempotency_requests
WHERE tenant_id = $1 AND method = $2 AND idempotency_key = $3
`

type GetIdempotencyParams struct {
	TenantID       pgtype.UUID
	Method         string
	IdempotencyKey string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (InferenceIdempotencyRequest, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.TenantID, arg.Method, arg.IdempotencyKey)
	var i InferenceIdempotencyRequest
	err := row.Scan(
		&i.TenantID,
		&i.Method,
		&i.IdempotencyKey,
		&i.PayloadHash,
		&i.OperationID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getLatestPublication = `-- name: GetLatestPublication :one
SELECT tenant_id, service_id, generation, desired_phase, observed_phase,
       invocation_url, owned_kind, owned_namespace, owned_name, owned_uid,
       owned_resource_version, last_error_code, observed_at, updated_at
FROM inference_publications
WHERE tenant_id = $1 AND service_id = $2 AND generation <= $3
ORDER BY generation DESC, updated_at DESC
LIMIT 1
`

type GetLatestPublicationParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetLatestPublication(ctx context.Context, arg GetLatestPublicationParams) (InferencePublication, error) {
	row := q.db.QueryRow(ctx, getLatestPublication, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferencePublication
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.Generation,
		&i.DesiredPhase,
		&i.ObservedPhase,
		&i.InvocationUrl,
		&i.OwnedKind,
		&i.OwnedNamespace,
		&i.OwnedName,
		&i.OwnedUid,
		&i.OwnedResourceVersion,
		&i.LastErrorCode,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestSpec = `-- name: GetLatestSpec :one
SELECT tenant_id, id, service_id, generation, model_id, model_version_id, artifact_provider, artifact_ref, artifact_sha256, image_ref, served_model_name, engine_runtime, command_argv, resources, replicas, spec_json, created_at, runtime_mode, worker_replicas, endpoint_container_port, endpoint_service_port, endpoint_target_port, endpoint_protocol FROM inference_specs
WHERE tenant_id = $1 AND service_id = $2 AND generation <= $3
ORDER BY generation DESC
LIMIT 1
`

type GetLatestSpecParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetLatestSpec(ctx context.Context, arg GetLatestSpecParams) (InferenceSpec, error) {
	row := q.db.QueryRow(ctx, getLatestSpec, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferenceSpec
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ServiceID,
		&i.Generation,
		&i.ModelID,
		&i.ModelVersionID,
		&i.ArtifactProvider,
		&i.ArtifactRef,
		&i.ArtifactSha256,
		&i.ImageRef,
		&i.ServedModelName,
		&i.EngineRuntime,
		&i.CommandArgv,
		&i.Resources,
		&i.Replicas,
		&i.SpecJson,
		&i.CreatedAt,
		&i.RuntimeMode,
		&i.WorkerReplicas,
		&i.EndpointContainerPort,
		&i.EndpointServicePort,
		&i.EndpointTargetPort,
		&i.EndpointProtocol,
	)
	return i, err
}

const getLeasedOperation = `-- name: GetLeasedOperation :one
SELECT o.tenant_id, o.id, o.service_id, o.kind, o.phase, o.step,
       o.target_generation, o.request_hash, o.attempt, o.retry_at,
       o.lease_owner, o.lease_until, o.lease_token, o.error_code,
       o.error_message, o.result_snapshot, o.created_at, o.updated_at,
       o.completed_at
FROM inference_operations o
JOIN inference_services s
  ON s.tenant_id = o.tenant_id AND s.id = o.service_id
JOIN inference_resource_work w
  ON w.tenant_id = o.tenant_id AND w.service_id = o.service_id
WHERE o.tenant_id = $1 AND o.id = s.current_operation_id
  AND o.target_generation = s.desired_generation
  AND w.lease_token = $2 AND w.lease_until > clock_timestamp()
`

type GetLeasedOperationParams struct {
	TenantID   pgtype.UUID
	LeaseToken pgtype.UUID
}

// The resource_work lease is the execution fence for operation steps.  A
// worker must reload the current operation while holding that lease.
func (q *Queries) GetLeasedOperation(ctx context.Context, arg GetLeasedOperationParams) (InferenceOperation, error) {
	row := q.db.QueryRow(ctx, getLeasedOperation, arg.TenantID, arg.LeaseToken)
	var i InferenceOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ServiceID,
		&i.Kind,
		&i.Phase,
		&i.Step,
		&i.TargetGeneration,
		&i.RequestHash,
		&i.Attempt,
		&i.RetryAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT tenant_id, id, service_id, kind, phase, step, target_generation, request_hash,
       attempt, retry_at, lease_owner, lease_until, lease_token,
       error_code, error_message, result_snapshot, created_at, updated_at, completed_at
FROM inference_operations
WHERE tenant_id = $1 AND id = $2
`

type GetOperationParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (InferenceOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.TenantID, arg.ID)
	var i InferenceOperation
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ServiceID,
		&i.Kind,
		&i.Phase,
		&i.Step,
		&i.TargetGeneration,
		&i.RequestHash,
		&i.Attempt,
		&i.RetryAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ResultSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOperationAuditContext = `-- name: GetOperationAuditContext :one
SELECT actor, request_id
FROM inference_audit_events
WHERE tenant_id = $1
  AND operation_id = $2
  AND event_type LIKE 'inference.%.accepted'
ORDER BY created_at ASC, event_id ASC
LIMIT 1
`

type GetOperationAuditContextParams struct {
	TenantID    pgtype.UUID
	OperationID pgtype.UUID
}

type GetOperationAuditContextRow struct {
	Actor     string
	RequestID string
}

// The acceptance event is the durable source of caller context. Worker step
// events reuse it after the synchronous request has returned.
func (q *Queries) GetOperationAuditContext(ctx context.Context, arg GetOperationAuditContextParams) (GetOperationAuditContextRow, error) {
	row := q.db.QueryRow(ctx, getOperationAuditContext, arg.TenantID, arg.OperationID)
	var i GetOperationAuditContextRow
	err := row.Scan(&i.Actor, &i.RequestID)
	return i, err
}

const getOperationService = `-- name: GetOperationService :one
SELECT service_id
FROM inference_operations
WHERE tenant_id = $1 AND id = $2
`

type GetOperationServiceParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

func (q *Queries) GetOperationService(ctx context.Context, arg GetOperationServiceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getOperationService, arg.TenantID, arg.ID)
	var service_id pgtype.UUID
	err := row.Scan(&service_id)
	return service_id, err
}

const getPreviousQuotaReservation = `-- name: GetPreviousQuotaReservation :one
SELECT tenant_id, service_id, operation_id, generation, reservation_id,
       requested_resources, state, last_error_code, created_at, updated_at
FROM inference_quota_reservations
WHERE tenant_id = $1 AND service_id = $2 AND generation < $3
  AND state IN ('reserved', 'confirmed', 'release_pending')
ORDER BY generation DESC, updated_at DESC
LIMIT 1
`

type GetPreviousQuotaReservationParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetPreviousQuotaReservation(ctx context.Context, arg GetPreviousQuotaReservationParams) (InferenceQuotaReservation, error) {
	row := q.db.QueryRow(ctx, getPreviousQuotaReservation, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferenceQuotaReservation
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.OperationID,
		&i.Generation,
		&i.ReservationID,
		&i.RequestedResources,
		&i.State,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublication = `-- name: GetPublication :one
SELECT tenant_id, service_id, generation, desired_phase, observed_phase,
       invocation_url, owned_kind, owned_namespace, owned_name, owned_uid,
       owned_resource_version, last_error_code, observed_at, updated_at
FROM inference_publications
WHERE tenant_id = $1 AND service_id = $2 AND generation = $3
`

type GetPublicationParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetPublication(ctx context.Context, arg GetPublicationParams) (InferencePublication, error) {
	row := q.db.QueryRow(ctx, getPublication, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferencePublication
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.Generation,
		&i.DesiredPhase,
		&i.ObservedPhase,
		&i.InvocationUrl,
		&i.OwnedKind,
		&i.OwnedNamespace,
		&i.OwnedName,
		&i.OwnedUid,
		&i.OwnedResourceVersion,
		&i.LastErrorCode,
		&i.ObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuotaReservation = `-- name: GetQuotaReservation :one
SELECT tenant_id, service_id, operation_id, generation, reservation_id,
       requested_resources, state, last_error_code, created_at, updated_at
FROM inference_quota_reservations
WHERE tenant_id = $1 AND operation_id = $2
`

type GetQuotaReservationParams struct {
	TenantID    pgtype.UUID
	OperationID pgtype.UUID
}

func (q *Queries) GetQuotaReservation(ctx context.Context, arg GetQuotaReservationParams) (InferenceQuotaReservation, error) {
	row := q.db.QueryRow(ctx, getQuotaReservation, arg.TenantID, arg.OperationID)
	var i InferenceQuotaReservation
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.OperationID,
		&i.Generation,
		&i.ReservationID,
		&i.RequestedResources,
		&i.State,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT rt.tenant_id, rt.service_id, rt.generation, rt.runtime_phase, rt.ready_replicas, rt.model_ready, rt.model_ready_known,
       COALESCE(pub.observed_phase, 'withdrawn') AS publication_phase,
       rt.invocation_health, rt.observed_at, rt.stale_after, rt.reason,
       rt.runtime_mode, rt.ready_groups, rt.ready_workers, rt.lws_uid
FROM inference_runtime rt
JOIN inference_services s ON s.tenant_id = rt.tenant_id AND s.id = rt.service_id
LEFT JOIN LATERAL (
  SELECT p.observed_phase FROM inference_publications p
  WHERE p.tenant_id = rt.tenant_id AND p.service_id = rt.service_id
    AND p.generation <= s.desired_generation
  ORDER BY p.generation DESC LIMIT 1
) pub ON TRUE
WHERE rt.tenant_id = $1 AND rt.service_id = $2
`

type GetRuntimeParams struct {
	TenantID  pgtype.UUID
	ServiceID pgtype.UUID
}

type GetRuntimeRow struct {
	TenantID         pgtype.UUID
	ServiceID        pgtype.UUID
	Generation       int64
	RuntimePhase     string
	ReadyReplicas    int32
	ModelReady       bool
	ModelReadyKnown  bool
	PublicationPhase string
	InvocationHealth string
	ObservedAt       pgtype.Timestamptz
	StaleAfter       pgtype.Timestamptz
	Reason           string
	RuntimeMode      string
	ReadyGroups      int32
	ReadyWorkers     int32
	LwsUid           string
}

// Publication is read from its owner table, not an independently stale
// runtime copy. Match ListServices so GET and LIST expose the same fact.
func (q *Queries) GetRuntime(ctx context.Context, arg GetRuntimeParams) (GetRuntimeRow, error) {
	row := q.db.QueryRow(ctx, getRuntime, arg.TenantID, arg.ServiceID)
	var i GetRuntimeRow
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.Generation,
		&i.RuntimePhase,
		&i.ReadyReplicas,
		&i.ModelReady,
		&i.ModelReadyKnown,
		&i.PublicationPhase,
		&i.InvocationHealth,
		&i.ObservedAt,
		&i.StaleAfter,
		&i.Reason,
		&i.RuntimeMode,
		&i.ReadyGroups,
		&i.ReadyWorkers,
		&i.LwsUid,
	)
	return i, err
}

const getRuntimeBinding = `-- name: GetRuntimeBinding :one
SELECT tenant_id, service_id, generation, object_kind, object_namespace,
       object_name, object_uid, resource_version, role, observed_at
FROM inference_runtime_bindings
WHERE tenant_id = $1
  AND service_id = $2
  AND generation = $3
  AND object_kind = $4
  AND role = $5
`

type GetRuntimeBindingParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
	ObjectKind string
	Role       string
}

func (q *Queries) GetRuntimeBinding(ctx context.Context, arg GetRuntimeBindingParams) (InferenceRuntimeBinding, error) {
	row := q.db.QueryRow(ctx, getRuntimeBinding,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.ObjectKind,
		arg.Role,
	)
	var i InferenceRuntimeBinding
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.Generation,
		&i.ObjectKind,
		&i.ObjectNamespace,
		&i.ObjectName,
		&i.ObjectUid,
		&i.ResourceVersion,
		&i.Role,
		&i.ObservedAt,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT tenant_id, id, name, desired_state, desired_generation, applied_generation, current_operation_id, deleted_at, created_at, updated_at
FROM inference_services
WHERE tenant_id = $1 AND id = $2
`

type GetServiceParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

type GetServiceRow struct {
	TenantID           pgtype.UUID
	ID                 pgtype.UUID
	Name               string
	DesiredState       string
	DesiredGeneration  int64
	AppliedGeneration  int64
	CurrentOperationID pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetService(ctx context.Context, arg GetServiceParams) (GetServiceRow, error) {
	row := q.db.QueryRow(ctx, getService, arg.TenantID, arg.ID)
	var i GetServiceRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.DesiredState,
		&i.DesiredGeneration,
		&i.AppliedGeneration,
		&i.CurrentOperationID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceForUpdate = `-- name: GetServiceForUpdate :one
SELECT tenant_id, id, name, desired_state, desired_generation, applied_generation, current_operation_id, deleted_at, created_at, updated_at
FROM inference_services
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type GetServiceForUpdateParams struct {
	TenantID pgtype.UUID
	ID       pgtype.UUID
}

type GetServiceForUpdateRow struct {
	TenantID           pgtype.UUID
	ID                 pgtype.UUID
	Name               string
	DesiredState       string
	DesiredGeneration  int64
	AppliedGeneration  int64
	CurrentOperationID pgtype.UUID
	DeletedAt          pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetServiceForUpdate(ctx context.Context, arg GetServiceForUpdateParams) (GetServiceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getServiceForUpdate, arg.TenantID, arg.ID)
	var i GetServiceForUpdateRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.DesiredState,
		&i.DesiredGeneration,
		&i.AppliedGeneration,
		&i.CurrentOperationID,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpec = `-- name: GetSpec :one
SELECT tenant_id, id, service_id, generation, model_id, model_version_id, artifact_provider, artifact_ref, artifact_sha256, image_ref, served_model_name, engine_runtime, command_argv, resources, replicas, spec_json, created_at, runtime_mode, worker_replicas, endpoint_container_port, endpoint_service_port, endpoint_target_port, endpoint_protocol FROM inference_specs
WHERE tenant_id = $1 AND service_id = $2 AND generation = $3
`

type GetSpecParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) GetSpec(ctx context.Context, arg GetSpecParams) (InferenceSpec, error) {
	row := q.db.QueryRow(ctx, getSpec, arg.TenantID, arg.ServiceID, arg.Generation)
	var i InferenceSpec
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ServiceID,
		&i.Generation,
		&i.ModelID,
		&i.ModelVersionID,
		&i.ArtifactProvider,
		&i.ArtifactRef,
		&i.ArtifactSha256,
		&i.ImageRef,
		&i.ServedModelName,
		&i.EngineRuntime,
		&i.CommandArgv,
		&i.Resources,
		&i.Replicas,
		&i.SpecJson,
		&i.CreatedAt,
		&i.RuntimeMode,
		&i.WorkerReplicas,
		&i.EndpointContainerPort,
		&i.EndpointServicePort,
		&i.EndpointTargetPort,
		&i.EndpointProtocol,
	)
	return i, err
}

const getStatusProjection = `-- name: GetStatusProjection :one
SELECT s.applied_generation,
       COALESCE(control.generation, 0)::bigint AS control_generation,
       COALESCE(control.object_namespace, '') AS control_namespace,
       COALESCE(control.object_name, '') AS control_name,
       COALESCE(control.object_uid, '') AS control_uid,
       COALESCE(rt.runtime_phase, 'unknown') AS runtime_phase,
       COALESCE(rt.ready_replicas, 0)::int4 AS ready_replicas,
       CASE WHEN rt.model_ready_known AND rt.model_ready THEN TRUE ELSE FALSE END AS model_ready,
       COALESCE(pub.observed_phase, 'withdrawn') AS publication_phase,
       CASE WHEN pub.generation = s.desired_generation
                  AND pub.desired_phase = 'published'
                  AND pub.observed_phase = 'published'
            THEN TRUE ELSE FALSE END AS publication_effective,
       COALESCE(rt.invocation_health, 'unknown') AS invocation_health,
       rt.observed_at AS observed_at,
       rt.stale_after AS runtime_stale_after,
       pub.observed_at AS publication_observed_at,
       rt.observed_at AS invocation_observed_at,
       op.id AS operation_id,
       op.kind AS operation_kind,
       op.phase AS operation_phase,
       op.step AS operation_step,
       op.error_message AS operation_message
FROM inference_services s
LEFT JOIN LATERAL (
  SELECT b.generation, b.object_namespace, b.object_name, b.object_uid
  FROM inference_runtime_bindings b
  WHERE b.tenant_id = s.tenant_id AND b.service_id = s.id
    AND b.object_kind = 'InferenceService' AND b.role = 'control'
    AND b.generation <= s.desired_generation
  ORDER BY b.generation DESC
  LIMIT 1
) control ON TRUE
LEFT JOIN inference_runtime rt
  ON rt.tenant_id = s.tenant_id AND rt.service_id = s.id
LEFT JOIN LATERAL (
  SELECT p.generation, p.desired_phase, p.observed_phase, p.observed_at
  FROM inference_publications p
  WHERE p.tenant_id = s.tenant_id
    AND p.service_id = s.id
    AND p.generation <= s.desired_generation
  ORDER BY p.generation DESC, p.updated_at DESC
  LIMIT 1
) pub ON TRUE
LEFT JOIN inference_operations op
  ON op.tenant_id = s.tenant_id AND op.id = s.current_operation_id
WHERE s.tenant_id = $1
  AND s.id = $2
  AND s.deleted_at IS NULL
`

type GetStatusProjectionParams struct {
	TenantID  pgtype.UUID
	ServiceID pgtype.UUID
}

type GetStatusProjectionRow struct {
	AppliedGeneration     int64
	ControlGeneration     int64
	ControlNamespace      string
	ControlName           string
	ControlUid            string
	RuntimePhase          string
	ReadyReplicas         int32
	ModelReady            bool
	PublicationPhase      string
	PublicationEffective  bool
	InvocationHealth      string
	ObservedAt            pgtype.Timestamptz
	RuntimeStaleAfter     pgtype.Timestamptz
	PublicationObservedAt pgtype.Timestamptz
	InvocationObservedAt  pgtype.Timestamptz
	OperationID           pgtype.UUID
	OperationKind         pgtype.Text
	OperationPhase        pgtype.Text
	OperationStep         pgtype.Text
	OperationMessage      pgtype.Text
}

// Read the complete status and binding snapshot in one statement, avoiding
// mixed snapshots across separate queries. Keep the latest publication fact
// at or below desired_generation so an older still-published route remains
// visible while its effective bit is fenced to the exact generation.
func (q *Queries) GetStatusProjection(ctx context.Context, arg GetStatusProjectionParams) (GetStatusProjectionRow, error) {
	row := q.db.QueryRow(ctx, getStatusProjection, arg.TenantID, arg.ServiceID)
	var i GetStatusProjectionRow
	err := row.Scan(
		&i.AppliedGeneration,
		&i.ControlGeneration,
		&i.ControlNamespace,
		&i.ControlName,
		&i.ControlUid,
		&i.RuntimePhase,
		&i.ReadyReplicas,
		&i.ModelReady,
		&i.PublicationPhase,
		&i.PublicationEffective,
		&i.InvocationHealth,
		&i.ObservedAt,
		&i.RuntimeStaleAfter,
		&i.PublicationObservedAt,
		&i.InvocationObservedAt,
		&i.OperationID,
		&i.OperationKind,
		&i.OperationPhase,
		&i.OperationStep,
		&i.OperationMessage,
	)
	return i, err
}

const getWorkMetrics = `-- name: GetWorkMetrics :one
SELECT
  (SELECT count(*)::bigint
   FROM inference_resource_work
   WHERE next_run_at IS NOT NULL AND next_run_at <= clock_timestamp()) AS due_work,
  COALESCE((SELECT EXTRACT(EPOCH FROM (clock_timestamp() - min(next_run_at)))
            FROM inference_resource_work
            WHERE next_run_at IS NOT NULL AND next_run_at <= clock_timestamp()), 0)::double precision AS oldest_work_age_seconds,
  (SELECT count(*)::bigint
   FROM inference_runtime rt
   JOIN inference_services s
     ON s.tenant_id = rt.tenant_id AND s.id = rt.service_id
   WHERE s.deleted_at IS NULL
     AND rt.stale_after IS NOT NULL AND rt.stale_after <= clock_timestamp()) AS stale_observations
`

type GetWorkMetricsRow struct {
	DueWork              int64
	OldestWorkAgeSeconds float64
	StaleObservations    int64
}

// Operational gauges are intentionally aggregate and contain no tenant or
// resource identifiers. The caller uses this only for low-cardinality metrics.
func (q *Queries) GetWorkMetrics(ctx context.Context) (GetWorkMetricsRow, error) {
	row := q.db.QueryRow(ctx, getWorkMetrics)
	var i GetWorkMetricsRow
	err := row.Scan(&i.DueWork, &i.OldestWorkAgeSeconds, &i.StaleObservations)
	return i, err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO inference_operations
  (tenant_id, id, service_id, kind, phase, step, target_generation, request_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertOperationParams struct {
	TenantID         pgtype.UUID
	ID               pgtype.UUID
	ServiceID        pgtype.UUID
	Kind             string
	Phase            string
	Step             string
	TargetGeneration int64
	RequestHash      string
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.TenantID,
		arg.ID,
		arg.ServiceID,
		arg.Kind,
		arg.Phase,
		arg.Step,
		arg.TargetGeneration,
		arg.RequestHash,
	)
	return err
}

const insertQuotaReservation = `-- name: InsertQuotaReservation :exec
INSERT INTO inference_quota_reservations
  (tenant_id, service_id, operation_id, generation, reservation_id, requested_resources, state)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
`

type InsertQuotaReservationParams struct {
	TenantID           pgtype.UUID
	ServiceID          pgtype.UUID
	OperationID        pgtype.UUID
	Generation         int64
	ReservationID      string
	RequestedResources []byte
}

func (q *Queries) InsertQuotaReservation(ctx context.Context, arg InsertQuotaReservationParams) error {
	_, err := q.db.Exec(ctx, insertQuotaReservation,
		arg.TenantID,
		arg.ServiceID,
		arg.OperationID,
		arg.Generation,
		arg.ReservationID,
		arg.RequestedResources,
	)
	return err
}

const insertRuntime = `-- name: InsertRuntime :exec
INSERT INTO inference_runtime
  (tenant_id, service_id, generation, runtime_mode, runtime_phase, publication_phase, invocation_health)
VALUES ($1, $2, $3, $4, 'unknown', 'withdrawn', 'unknown')
`

type InsertRuntimeParams struct {
	TenantID    pgtype.UUID
	ServiceID   pgtype.UUID
	Generation  int64
	RuntimeMode string
}

func (q *Queries) InsertRuntime(ctx context.Context, arg InsertRuntimeParams) error {
	_, err := q.db.Exec(ctx, insertRuntime,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.RuntimeMode,
	)
	return err
}

const insertService = `-- name: InsertService :exec
INSERT INTO inference_services
  (tenant_id, id, name, desired_state, desired_generation, current_operation_id)
VALUES ($1, $2, $3, $4, $5, NULL)
`

type InsertServiceParams struct {
	TenantID          pgtype.UUID
	ID                pgtype.UUID
	Name              string
	DesiredState      string
	DesiredGeneration int64
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) error {
	_, err := q.db.Exec(ctx, insertService,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.DesiredState,
		arg.DesiredGeneration,
	)
	return err
}

const insertSpec = `-- name: InsertSpec :exec
INSERT INTO inference_specs
  (tenant_id, id, service_id, generation, model_id, model_version_id,
   artifact_provider, artifact_ref, artifact_sha256, image_ref, served_model_name,
   engine_runtime, command_argv, resources, replicas, runtime_mode, worker_replicas, spec_json,
   endpoint_container_port, endpoint_service_port, endpoint_target_port, endpoint_protocol)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18,
        $19, $20, $21, $22)
`

type InsertSpecParams struct {
	TenantID              pgtype.UUID
	ID                    pgtype.UUID
	ServiceID             pgtype.UUID
	Generation            int64
	ModelID               pgtype.UUID
	ModelVersionID        pgtype.UUID
	ArtifactProvider      string
	ArtifactRef           string
	ArtifactSha256        string
	ImageRef              string
	ServedModelName       string
	EngineRuntime         string
	CommandArgv           []byte
	Resources             []byte
	Replicas              int32
	RuntimeMode           string
	WorkerReplicas        int32
	SpecJson              []byte
	EndpointContainerPort pgtype.Int4
	EndpointServicePort   pgtype.Int4
	EndpointTargetPort    pgtype.Text
	EndpointProtocol      pgtype.Text
}

func (q *Queries) InsertSpec(ctx context.Context, arg InsertSpecParams) error {
	_, err := q.db.Exec(ctx, insertSpec,
		arg.TenantID,
		arg.ID,
		arg.ServiceID,
		arg.Generation,
		arg.ModelID,
		arg.ModelVersionID,
		arg.ArtifactProvider,
		arg.ArtifactRef,
		arg.ArtifactSha256,
		arg.ImageRef,
		arg.ServedModelName,
		arg.EngineRuntime,
		arg.CommandArgv,
		arg.Resources,
		arg.Replicas,
		arg.RuntimeMode,
		arg.WorkerReplicas,
		arg.SpecJson,
		arg.EndpointContainerPort,
		arg.EndpointServicePort,
		arg.EndpointTargetPort,
		arg.EndpointProtocol,
	)
	return err
}

const listCurrentRuntimeBindings = `-- name: ListCurrentRuntimeBindings :many
SELECT DISTINCT ON (object_kind, role)
       tenant_id, service_id, generation, object_kind, object_namespace,
       object_name, object_uid, resource_version, role, observed_at
FROM inference_runtime_bindings
WHERE tenant_id = $1 AND service_id = $2 AND generation <= $3
ORDER BY object_kind, role, generation DESC
`

type ListCurrentRuntimeBindingsParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

// Lifecycle commands advance desired generation before removing the last
// applied runtime. Keep its latest recorded identity until removal is proven.
func (q *Queries) ListCurrentRuntimeBindings(ctx context.Context, arg ListCurrentRuntimeBindingsParams) ([]InferenceRuntimeBinding, error) {
	rows, err := q.db.Query(ctx, listCurrentRuntimeBindings, arg.TenantID, arg.ServiceID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceRuntimeBinding
	for rows.Next() {
		var i InferenceRuntimeBinding
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceID,
			&i.Generation,
			&i.ObjectKind,
			&i.ObjectNamespace,
			&i.ObjectName,
			&i.ObjectUid,
			&i.ResourceVersion,
			&i.Role,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperations = `-- name: ListOperations :many
SELECT tenant_id, id, service_id, kind, phase, step, target_generation,
       request_hash, attempt, retry_at, lease_owner, lease_until, lease_token,
       error_code, error_message, result_snapshot, created_at, updated_at,
       completed_at
FROM inference_operations
WHERE tenant_id = $1
  AND ($2::uuid IS NULL OR service_id = $2::uuid)
  AND ($3::timestamptz IS NULL
       OR (created_at, id) <
          ($3::timestamptz, $4::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOperationsParams struct {
	TenantID        pgtype.UUID
	ServiceID       pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

func (q *Queries) ListOperations(ctx context.Context, arg ListOperationsParams) ([]InferenceOperation, error) {
	rows, err := q.db.Query(ctx, listOperations,
		arg.TenantID,
		arg.ServiceID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceOperation
	for rows.Next() {
		var i InferenceOperation
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ServiceID,
			&i.Kind,
			&i.Phase,
			&i.Step,
			&i.TargetGeneration,
			&i.RequestHash,
			&i.Attempt,
			&i.RetryAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.LeaseToken,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ResultSnapshot,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeBindings = `-- name: ListRuntimeBindings :many
SELECT tenant_id, service_id, generation, object_kind, object_namespace,
       object_name, object_uid, resource_version, role, observed_at
FROM inference_runtime_bindings
WHERE tenant_id = $1 AND service_id = $2 AND generation <= $3
ORDER BY object_kind, role
`

type ListRuntimeBindingsParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
}

func (q *Queries) ListRuntimeBindings(ctx context.Context, arg ListRuntimeBindingsParams) ([]InferenceRuntimeBinding, error) {
	rows, err := q.db.Query(ctx, listRuntimeBindings, arg.TenantID, arg.ServiceID, arg.Generation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceRuntimeBinding
	for rows.Next() {
		var i InferenceRuntimeBinding
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceID,
			&i.Generation,
			&i.ObjectKind,
			&i.ObjectNamespace,
			&i.ObjectName,
			&i.ObjectUid,
			&i.ResourceVersion,
			&i.Role,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT s.tenant_id, s.id, s.name, s.desired_state, s.desired_generation, s.applied_generation,
       s.created_at,
       sp.model_version_id AS model_version_id,
       COALESCE(sp.artifact_provider, '') AS artifact_provider,
       COALESCE(sp.artifact_ref, '') AS artifact_ref,
       COALESCE(sp.artifact_sha256, '') AS artifact_sha256,
       COALESCE(sp.image_ref, '') AS image_ref,
       COALESCE(sp.served_model_name, '') AS served_model_name,
       COALESCE(sp.engine_runtime, '') AS engine_runtime,
       COALESCE(sp.command_argv, '[]'::jsonb) AS command_argv,
       COALESCE(sp.resources, '{}'::jsonb) AS resources,
       COALESCE(sp.replicas, 0)::int4 AS replicas,
       COALESCE(sp.runtime_mode, 'deployment') AS runtime_mode,
       COALESCE(sp.worker_replicas, 1)::int4 AS worker_replicas,
       sp.endpoint_container_port, sp.endpoint_service_port,
       sp.endpoint_target_port, sp.endpoint_protocol,
       COALESCE(rt.runtime_phase, 'unknown') AS runtime_phase,
       COALESCE(pub.observed_phase, 'withdrawn') AS publication_phase,
       COALESCE(rt.invocation_health, 'unknown') AS invocation_health,
       rt.observed_at
FROM inference_services s
LEFT JOIN inference_specs sp
  ON sp.tenant_id = s.tenant_id AND sp.service_id = s.id
 AND sp.generation = s.desired_generation
LEFT JOIN inference_runtime rt
  ON rt.tenant_id = s.tenant_id AND rt.service_id = s.id
LEFT JOIN LATERAL (
  SELECT p.observed_phase FROM inference_publications p
  WHERE p.tenant_id = s.tenant_id AND p.service_id = s.id
    AND p.generation <= s.desired_generation
  ORDER BY p.generation DESC LIMIT 1
) pub ON TRUE
WHERE s.tenant_id = $1
  AND s.deleted_at IS NULL
  AND ($2::timestamptz IS NULL
       OR (s.created_at, s.id) <
          ($2::timestamptz, $3::uuid))
ORDER BY s.created_at DESC, s.id DESC
LIMIT $4
`

type ListServicesParams struct {
	TenantID        pgtype.UUID
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	PageSize        int32
}

type ListServicesRow struct {
	TenantID              pgtype.UUID
	ID                    pgtype.UUID
	Name                  string
	DesiredState          string
	DesiredGeneration     int64
	AppliedGeneration     int64
	CreatedAt             pgtype.Timestamptz
	ModelVersionID        pgtype.UUID
	ArtifactProvider      string
	ArtifactRef           string
	ArtifactSha256        string
	ImageRef              string
	ServedModelName       string
	EngineRuntime         string
	CommandArgv           []byte
	Resources             []byte
	Replicas              int32
	RuntimeMode           string
	WorkerReplicas        int32
	EndpointContainerPort pgtype.Int4
	EndpointServicePort   pgtype.Int4
	EndpointTargetPort    pgtype.Text
	EndpointProtocol      pgtype.Text
	RuntimePhase          string
	PublicationPhase      string
	InvocationHealth      string
	ObservedAt            pgtype.Timestamptz
}

// The cursor is the (created_at, id) key of the last row returned.  Both
// predicates and the ordering are tenant-scoped and stable under inserts.
func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices,
		arg.TenantID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.Name,
			&i.DesiredState,
			&i.DesiredGeneration,
			&i.AppliedGeneration,
			&i.CreatedAt,
			&i.ModelVersionID,
			&i.ArtifactProvider,
			&i.ArtifactRef,
			&i.ArtifactSha256,
			&i.ImageRef,
			&i.ServedModelName,
			&i.EngineRuntime,
			&i.CommandArgv,
			&i.Resources,
			&i.Replicas,
			&i.RuntimeMode,
			&i.WorkerReplicas,
			&i.EndpointContainerPort,
			&i.EndpointServicePort,
			&i.EndpointTargetPort,
			&i.EndpointProtocol,
			&i.RuntimePhase,
			&i.PublicationPhase,
			&i.InvocationHealth,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdempotency = `-- name: LockIdempotency :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    $1::text || ':' || $2::text || ':' || $3::text, 0))
`

type LockIdempotencyParams struct {
	TenantID       string
	Method         string
	IdempotencyKey string
}

// Serialize same command identities before mutating the aggregate. Hash
// collisions only serialize unrelated commands; tenant predicates remain on
// every subsequent data access.
func (q *Queries) LockIdempotency(ctx context.Context, arg LockIdempotencyParams) error {
	_, err := q.db.Exec(ctx, lockIdempotency, arg.TenantID, arg.Method, arg.IdempotencyKey)
	return err
}

const markModelMaterializingForWork = `-- name: MarkModelMaterializingForWork :execrows
UPDATE inference_runtime r
SET model_ready = FALSE, model_ready_known = FALSE, observed_at = now(),
    stale_after = now() + interval '2 minutes',
    updated_at = now(), reason = 'model materialization pending'
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE r.tenant_id = $1 AND r.service_id = $2
  AND s.tenant_id = r.tenant_id AND s.id = r.service_id
  AND s.desired_generation = $3
  AND r.generation <= $3
  AND w.lease_token = $4
  AND w.lease_until > clock_timestamp()
`

type MarkModelMaterializingForWorkParams struct {
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
	LeaseToken pgtype.UUID
}

// Clear a previous generation's model-ready fact before a new materialization
// attempt so stale readiness cannot authorize publication.
func (q *Queries) MarkModelMaterializingForWork(ctx context.Context, arg MarkModelMaterializingForWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, markModelMaterializingForWork,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceAppliedGeneration = `-- name: MarkServiceAppliedGeneration :execrows
UPDATE inference_services
SET applied_generation = GREATEST(applied_generation, $1),
    updated_at = clock_timestamp()
WHERE tenant_id = $2 AND id = $3
  AND desired_generation = $1
  AND deleted_at IS NULL
`

type MarkServiceAppliedGenerationParams struct {
	Generation int64
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
}

// The observation CAS has already fenced the lease/generation in the same
// transaction. This projection records the latest generation observed after
// runtime application without replacing desired_generation.
func (q *Queries) MarkServiceAppliedGeneration(ctx context.Context, arg MarkServiceAppliedGenerationParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceAppliedGeneration, arg.Generation, arg.TenantID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markServiceDeleted = `-- name: MarkServiceDeleted :execrows
UPDATE inference_services
SET deleted_at = COALESCE(deleted_at, clock_timestamp()), updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND current_operation_id = $3
  AND desired_state = 'deleted' AND desired_generation = $4
`

type MarkServiceDeletedParams struct {
	TenantID           pgtype.UUID
	ID                 pgtype.UUID
	CurrentOperationID pgtype.UUID
	DesiredGeneration  int64
}

func (q *Queries) MarkServiceDeleted(ctx context.Context, arg MarkServiceDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markServiceDeleted,
		arg.TenantID,
		arg.ID,
		arg.CurrentOperationID,
		arg.DesiredGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const putIdempotency = `-- name: PutIdempotency :execrows
INSERT INTO inference_idempotency_requests
  (tenant_id, method, idempotency_key, payload_hash, operation_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, method, idempotency_key) DO NOTHING
`

type PutIdempotencyParams struct {
	TenantID       pgtype.UUID
	Method         string
	IdempotencyKey string
	PayloadHash    string
	OperationID    pgtype.UUID
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) PutIdempotency(ctx context.Context, arg PutIdempotencyParams) (int64, error) {
	result, err := q.db.Exec(ctx, putIdempotency,
		arg.TenantID,
		arg.Method,
		arg.IdempotencyKey,
		arg.PayloadHash,
		arg.OperationID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryOperationStepCAS = `-- name: RetryOperationStepCAS :execrows
UPDATE inference_operations o
SET phase = 'pending',
    attempt = o.attempt + 1,
    retry_at = clock_timestamp() + $1::double precision * interval '1 second',
    lease_owner = NULL,
    lease_until = NULL,
    lease_token = NULL,
    error_code = $2,
    error_message = $3,
    updated_at = clock_timestamp()
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE o.tenant_id = $4
  AND o.id = $5
  AND o.target_generation = $6
  AND o.phase = $7
  AND o.step = $8
  AND s.tenant_id = o.tenant_id
  AND s.id = o.service_id
  AND s.current_operation_id = o.id
  AND s.desired_generation = o.target_generation
  AND w.lease_token = $9
  AND w.lease_until > clock_timestamp()
`

type RetryOperationStepCASParams struct {
	RetrySeconds     float64
	ErrorCode        string
	ErrorMessage     string
	TenantID         pgtype.UUID
	OperationID      pgtype.UUID
	TargetGeneration int64
	ExpectedPhase    string
	ExpectedStep     string
	LeaseToken       pgtype.UUID
}

// Retry keeps the step durable and schedules another attempt.  It is fenced
// by the same aggregate/generation predicates as a normal step transition.
func (q *Queries) RetryOperationStepCAS(ctx context.Context, arg RetryOperationStepCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryOperationStepCAS,
		arg.RetrySeconds,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.TenantID,
		arg.OperationID,
		arg.TargetGeneration,
		arg.ExpectedPhase,
		arg.ExpectedStep,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCurrentOperation = `-- name: SetCurrentOperation :exec
UPDATE inference_services
SET current_operation_id = $3, updated_at = now()
WHERE tenant_id = $1 AND id = $2
`

type SetCurrentOperationParams struct {
	TenantID           pgtype.UUID
	ID                 pgtype.UUID
	CurrentOperationID pgtype.UUID
}

func (q *Queries) SetCurrentOperation(ctx context.Context, arg SetCurrentOperationParams) error {
	_, err := q.db.Exec(ctx, setCurrentOperation, arg.TenantID, arg.ID, arg.CurrentOperationID)
	return err
}

const transitionService = `-- name: TransitionService :execrows
UPDATE inference_services
SET desired_state = $1, desired_generation = $2,
    current_operation_id = $3, updated_at = now()
WHERE tenant_id = $4 AND id = $5
  AND desired_generation = $6 AND deleted_at IS NULL
`

type TransitionServiceParams struct {
	DesiredState       string
	TargetGeneration   int64
	OperationID        pgtype.UUID
	TenantID           pgtype.UUID
	ServiceID          pgtype.UUID
	ExpectedGeneration int64
}

func (q *Queries) TransitionService(ctx context.Context, arg TransitionServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, transitionService,
		arg.DesiredState,
		arg.TargetGeneration,
		arg.OperationID,
		arg.TenantID,
		arg.ServiceID,
		arg.ExpectedGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateModelObservationForWork = `-- name: UpdateModelObservationForWork :execrows
UPDATE inference_runtime r
SET model_ready = $1, observed_at = now(),
    model_ready_known = TRUE,
    stale_after = now() + interval '2 minutes',
    updated_at = now(), reason = $2
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE r.tenant_id = $3 AND r.service_id = $4
  AND s.tenant_id = r.tenant_id AND s.id = r.service_id
  AND s.desired_generation = $5
  AND r.generation <= $5
  AND w.lease_token = $6
  AND w.lease_until > clock_timestamp()
`

type UpdateModelObservationForWorkParams struct {
	ModelReady bool
	Reason     string
	TenantID   pgtype.UUID
	ServiceID  pgtype.UUID
	Generation int64
	LeaseToken pgtype.UUID
}

// Model materialization updates only its own fact while preserving runtime,
// publication, and invocation fields written by other observers.
func (q *Queries) UpdateModelObservationForWork(ctx context.Context, arg UpdateModelObservationForWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateModelObservationForWork,
		arg.ModelReady,
		arg.Reason,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateObservationCAS = `-- name: UpdateObservationCAS :execrows
UPDATE inference_runtime r
SET generation = $1, runtime_mode = $2,
    ready_groups = $3, ready_workers = $4,
    lws_uid = $5, runtime_phase = $6,
    ready_replicas = $7, model_ready = $8,
    publication_phase = $9,
    invocation_health = $10, observed_at = now(),
    stale_after = now() + interval '2 minutes',
    updated_at = now(), reason = $11
FROM inference_services s
WHERE r.tenant_id = $12 AND r.service_id = $13
  AND s.tenant_id = r.tenant_id AND s.id = r.service_id
  AND s.desired_generation = $1
  AND r.generation <= $1
`

type UpdateObservationCASParams struct {
	Generation       int64
	RuntimeMode      string
	ReadyGroups      int32
	ReadyWorkers     int32
	LwsUid           string
	RuntimePhase     string
	ReadyReplicas    int32
	ModelReady       bool
	PublicationPhase string
	InvocationHealth string
	Reason           string
	TenantID         pgtype.UUID
	ServiceID        pgtype.UUID
}

func (q *Queries) UpdateObservationCAS(ctx context.Context, arg UpdateObservationCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateObservationCAS,
		arg.Generation,
		arg.RuntimeMode,
		arg.ReadyGroups,
		arg.ReadyWorkers,
		arg.LwsUid,
		arg.RuntimePhase,
		arg.ReadyReplicas,
		arg.ModelReady,
		arg.PublicationPhase,
		arg.InvocationHealth,
		arg.Reason,
		arg.TenantID,
		arg.ServiceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateObservationForWork = `-- name: UpdateObservationForWork :execrows
UPDATE inference_runtime r
SET generation = $1, runtime_mode = $2,
    ready_groups = $3, ready_workers = $4,
    lws_uid = $5, runtime_phase = $6,
    ready_replicas = $7, model_ready = $8,
    publication_phase = $9,
    invocation_health = $10, observed_at = now(),
    stale_after = now() + interval '2 minutes',
    updated_at = now(), reason = $11
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE r.tenant_id = $12 AND r.service_id = $13
  AND s.tenant_id = r.tenant_id AND s.id = r.service_id
  AND s.desired_generation = $1
  AND r.generation <= $1
  AND w.lease_token = $14
  AND w.lease_until > clock_timestamp()
`

type UpdateObservationForWorkParams struct {
	Generation       int64
	RuntimeMode      string
	ReadyGroups      int32
	ReadyWorkers     int32
	LwsUid           string
	RuntimePhase     string
	ReadyReplicas    int32
	ModelReady       bool
	PublicationPhase string
	InvocationHealth string
	Reason           string
	TenantID         pgtype.UUID
	ServiceID        pgtype.UUID
	LeaseToken       pgtype.UUID
}

// Observation writes are fenced by the same durable work lease used for the
// runtime call. A late worker cannot overwrite a newer claim or generation.
func (q *Queries) UpdateObservationForWork(ctx context.Context, arg UpdateObservationForWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateObservationForWork,
		arg.Generation,
		arg.RuntimeMode,
		arg.ReadyGroups,
		arg.ReadyWorkers,
		arg.LwsUid,
		arg.RuntimePhase,
		arg.ReadyReplicas,
		arg.ModelReady,
		arg.PublicationPhase,
		arg.InvocationHealth,
		arg.Reason,
		arg.TenantID,
		arg.ServiceID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQuotaReservation = `-- name: UpdateQuotaReservation :execrows
UPDATE inference_quota_reservations
SET reservation_id = $3, requested_resources = $4, state = $5,
    last_error_code = $6, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND operation_id = $2 AND generation = $7
`

type UpdateQuotaReservationParams struct {
	TenantID           pgtype.UUID
	OperationID        pgtype.UUID
	ReservationID      string
	RequestedResources []byte
	State              string
	LastErrorCode      string
	Generation         int64
}

func (q *Queries) UpdateQuotaReservation(ctx context.Context, arg UpdateQuotaReservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuotaReservation,
		arg.TenantID,
		arg.OperationID,
		arg.ReservationID,
		arg.RequestedResources,
		arg.State,
		arg.LastErrorCode,
		arg.Generation,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateQuotaReservationFenced = `-- name: UpdateQuotaReservationFenced :execrows
UPDATE inference_quota_reservations r
SET reservation_id = $1, requested_resources = $2, state = $3,
    last_error_code = $4, updated_at = clock_timestamp()
FROM inference_operations o
JOIN inference_resource_work w
  ON w.tenant_id = o.tenant_id AND w.service_id = o.service_id
JOIN inference_services s
  ON s.tenant_id = o.tenant_id AND s.id = o.service_id
WHERE r.tenant_id = $5 AND r.operation_id = $6
  AND r.generation = $7
  AND o.tenant_id = r.tenant_id
  AND o.target_generation >= r.generation
  AND o.id = $8
  AND s.current_operation_id = o.id
  AND w.lease_token = $9 AND w.lease_until > clock_timestamp()
`

type UpdateQuotaReservationFencedParams struct {
	ReservationID      string
	RequestedResources []byte
	State              string
	LastErrorCode      string
	TenantID           pgtype.UUID
	OperationID        pgtype.UUID
	Generation         int64
	FenceOperationID   pgtype.UUID
	LeaseToken         pgtype.UUID
}

func (q *Queries) UpdateQuotaReservationFenced(ctx context.Context, arg UpdateQuotaReservationFencedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateQuotaReservationFenced,
		arg.ReservationID,
		arg.RequestedResources,
		arg.State,
		arg.LastErrorCode,
		arg.TenantID,
		arg.OperationID,
		arg.Generation,
		arg.FenceOperationID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPublication = `-- name: UpsertPublication :exec
INSERT INTO inference_publications
  (tenant_id, service_id, generation, desired_phase, observed_phase,
   invocation_url, last_error_code)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, service_id, generation) DO UPDATE
SET desired_phase = EXCLUDED.desired_phase,
    observed_phase = CASE
      WHEN EXCLUDED.desired_phase IN ('publishing', 'withdrawing')
        THEN inference_publications.observed_phase
      ELSE EXCLUDED.observed_phase
    END,
    invocation_url = EXCLUDED.invocation_url,
    last_error_code = EXCLUDED.last_error_code,
    updated_at = clock_timestamp()
`

type UpsertPublicationParams struct {
	TenantID      pgtype.UUID
	ServiceID     pgtype.UUID
	Generation    int64
	DesiredPhase  string
	ObservedPhase string
	InvocationUrl string
	LastErrorCode string
}

func (q *Queries) UpsertPublication(ctx context.Context, arg UpsertPublicationParams) error {
	_, err := q.db.Exec(ctx, upsertPublication,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.DesiredPhase,
		arg.ObservedPhase,
		arg.InvocationUrl,
		arg.LastErrorCode,
	)
	return err
}

const upsertPublicationFenced = `-- name: UpsertPublicationFenced :execrows
INSERT INTO inference_publications
  (tenant_id, service_id, generation, desired_phase, observed_phase,
   invocation_url, last_error_code)
SELECT $1, $2, $3, $4, $5, $6, $7
WHERE EXISTS (
  SELECT 1
  FROM inference_operations o
  JOIN inference_resource_work w
    ON w.tenant_id = o.tenant_id AND w.service_id = o.service_id
  JOIN inference_services s
    ON s.tenant_id = o.tenant_id AND s.id = o.service_id
  WHERE o.tenant_id = $1 AND o.id = $8
    AND o.target_generation >= $3
    AND s.current_operation_id = o.id
    AND w.lease_token = $9 AND w.lease_until > clock_timestamp()
)
ON CONFLICT (tenant_id, service_id, generation) DO UPDATE
SET desired_phase = EXCLUDED.desired_phase,
    observed_phase = CASE
      WHEN EXCLUDED.desired_phase IN ('publishing', 'withdrawing')
        THEN inference_publications.observed_phase
      ELSE EXCLUDED.observed_phase
    END,
    invocation_url = EXCLUDED.invocation_url,
    last_error_code = EXCLUDED.last_error_code,
    updated_at = clock_timestamp()
`

type UpsertPublicationFencedParams struct {
	TenantID         pgtype.UUID
	ServiceID        pgtype.UUID
	Generation       int64
	DesiredPhase     string
	ObservedPhase    string
	InvocationUrl    string
	LastErrorCode    string
	FenceOperationID pgtype.UUID
	LeaseToken       pgtype.UUID
}

func (q *Queries) UpsertPublicationFenced(ctx context.Context, arg UpsertPublicationFencedParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertPublicationFenced,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.DesiredPhase,
		arg.ObservedPhase,
		arg.InvocationUrl,
		arg.LastErrorCode,
		arg.FenceOperationID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertResourceWork = `-- name: UpsertResourceWork :exec
INSERT INTO inference_resource_work (tenant_id, service_id, dirty_version, acknowledged_version)
VALUES ($1, $2, $3, 0)
ON CONFLICT (tenant_id, service_id) DO UPDATE
SET dirty_version = GREATEST(inference_resource_work.dirty_version + 1, EXCLUDED.dirty_version),
    next_run_at = clock_timestamp(),
    updated_at = clock_timestamp()
`

type UpsertResourceWorkParams struct {
	TenantID     pgtype.UUID
	ServiceID    pgtype.UUID
	DirtyVersion int64
}

// dirty_version is a durable notification sequence, not the business
// generation. Every event (including a same/older generation status event)
// increments it so a notification received while a worker is running cannot
// be hidden by that worker's acknowledgement. The service generation remains
// read from inference_services by Claim/Commit CAS.
func (q *Queries) UpsertResourceWork(ctx context.Context, arg UpsertResourceWorkParams) error {
	_, err := q.db.Exec(ctx, upsertResourceWork, arg.TenantID, arg.ServiceID, arg.DirtyVersion)
	return err
}

const upsertRuntimeBindingCAS = `-- name: UpsertRuntimeBindingCAS :execrows
INSERT INTO inference_runtime_bindings
  (tenant_id, service_id, generation, object_kind, object_namespace,
   object_name, object_uid, resource_version, role)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tenant_id, service_id, generation, object_kind, role) DO UPDATE
SET object_namespace = EXCLUDED.object_namespace,
    object_name = EXCLUDED.object_name,
    object_uid = EXCLUDED.object_uid,
    resource_version = EXCLUDED.resource_version,
    observed_at = clock_timestamp()
WHERE inference_runtime_bindings.object_uid = EXCLUDED.object_uid
  AND inference_runtime_bindings.object_namespace = EXCLUDED.object_namespace
  AND inference_runtime_bindings.object_name = EXCLUDED.object_name
  AND ((inference_runtime_bindings.object_uid = $10
        AND inference_runtime_bindings.resource_version = $11)
       OR ($10 = ''
           AND $11 = ''
           AND inference_runtime_bindings.resource_version = EXCLUDED.resource_version))
`

type UpsertRuntimeBindingCASParams struct {
	TenantID                pgtype.UUID
	ServiceID               pgtype.UUID
	Generation              int64
	ObjectKind              string
	ObjectNamespace         string
	ObjectName              string
	ObjectUid               string
	ResourceVersion         string
	Role                    string
	ExpectedUid             string
	ExpectedResourceVersion string
}

// An insert creates the binding.  An update is accepted only when both
// fencing values still match the values the caller read.  Kubernetes
// resourceVersion is opaque and is compared only for equality. An exact
// replay of an initial insert is a no-op that refreshes observed_at.
func (q *Queries) UpsertRuntimeBindingCAS(ctx context.Context, arg UpsertRuntimeBindingCASParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertRuntimeBindingCAS,
		arg.TenantID,
		arg.ServiceID,
		arg.Generation,
		arg.ObjectKind,
		arg.ObjectNamespace,
		arg.ObjectName,
		arg.ObjectUid,
		arg.ResourceVersion,
		arg.Role,
		arg.ExpectedUid,
		arg.ExpectedResourceVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
