// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_reference.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasActiveModelVersionReferences = `-- name: HasActiveModelVersionReferences :one
SELECT EXISTS (
 SELECT 1 FROM inference_specs sp
 JOIN inference_services s ON s.tenant_id=sp.tenant_id AND s.id=sp.service_id
 WHERE sp.tenant_id=$1 AND sp.model_version_id=ANY($2::uuid[])
   AND s.deleted_at IS NULL
) AS has_active_references
`

type HasActiveModelVersionReferencesParams struct {
	TenantID pgtype.UUID
	Column2  []pgtype.UUID
}

func (q *Queries) HasActiveModelVersionReferences(ctx context.Context, arg HasActiveModelVersionReferencesParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveModelVersionReferences, arg.TenantID, arg.Column2)
	var has_active_references bool
	err := row.Scan(&has_active_references)
	return has_active_references, err
}
