// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimResourceWork = `-- name: ClaimResourceWork :one
WITH candidate AS (
    SELECT w.tenant_id, w.service_id, s.desired_generation
    FROM inference_resource_work w
    JOIN inference_services s ON s.tenant_id = w.tenant_id AND s.id = w.service_id
    WHERE w.tenant_id = $4
      AND s.deleted_at IS NULL
      AND (w.lease_until IS NULL OR w.lease_until <= clock_timestamp())
      AND (
        (w.next_run_at IS NOT NULL AND w.next_run_at <= clock_timestamp())
        OR (w.next_run_at IS NULL AND w.acknowledged_version < w.dirty_version)
      )
    ORDER BY w.next_run_at NULLS FIRST, w.updated_at, w.service_id
    LIMIT 1
    FOR UPDATE OF w SKIP LOCKED
)
UPDATE inference_resource_work w
SET lease_owner = $1,
    lease_token = $2,
    lease_until = clock_timestamp() + $3::double precision * interval '1 second',
    attempt = w.attempt + 1,
    updated_at = clock_timestamp()
FROM candidate c
WHERE w.tenant_id = c.tenant_id AND w.service_id = c.service_id
RETURNING w.tenant_id, w.service_id, w.dirty_version, c.desired_generation, w.lease_token
`

type ClaimResourceWorkParams struct {
	LeaseOwner   pgtype.Text
	LeaseToken   pgtype.UUID
	LeaseSeconds float64
	TenantID     pgtype.UUID
}

type ClaimResourceWorkRow struct {
	TenantID          pgtype.UUID
	ServiceID         pgtype.UUID
	DirtyVersion      int64
	DesiredGeneration int64
	LeaseToken        pgtype.UUID
}

func (q *Queries) ClaimResourceWork(ctx context.Context, arg ClaimResourceWorkParams) (ClaimResourceWorkRow, error) {
	row := q.db.QueryRow(ctx, claimResourceWork,
		arg.LeaseOwner,
		arg.LeaseToken,
		arg.LeaseSeconds,
		arg.TenantID,
	)
	var i ClaimResourceWorkRow
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.DirtyVersion,
		&i.DesiredGeneration,
		&i.LeaseToken,
	)
	return i, err
}

const commitResourceWork = `-- name: CommitResourceWork :execrows
UPDATE inference_resource_work w
SET acknowledged_version = GREATEST(w.acknowledged_version, $1::bigint),
    next_run_at = CASE
        WHEN s.deleted_at IS NOT NULL THEN NULL
        WHEN w.dirty_version > $1::bigint THEN clock_timestamp()
        ELSE clock_timestamp() + $2::double precision * interval '1 second'
    END,
    attempt = 0,
    lease_owner = NULL, lease_until = NULL, lease_token = NULL,
    last_error_code = '', updated_at = clock_timestamp()
FROM inference_services s
WHERE w.tenant_id = $3 AND w.service_id = $4
  AND s.tenant_id = w.tenant_id AND s.id = w.service_id
  AND s.desired_generation = $5
  AND w.lease_token = $6
  AND w.lease_until > clock_timestamp()
  AND $1::bigint BETWEEN 0 AND w.dirty_version
`

type CommitResourceWorkParams struct {
	ClaimedDirtyVersion int64
	ObserveSeconds      float64
	TenantID            pgtype.UUID
	ServiceID           pgtype.UUID
	DesiredGeneration   int64
	LeaseToken          pgtype.UUID
}

func (q *Queries) CommitResourceWork(ctx context.Context, arg CommitResourceWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, commitResourceWork,
		arg.ClaimedDirtyVersion,
		arg.ObserveSeconds,
		arg.TenantID,
		arg.ServiceID,
		arg.DesiredGeneration,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLeasedDesired = `-- name: GetLeasedDesired :one
SELECT s.tenant_id, s.id, s.desired_generation
FROM inference_services s
JOIN inference_resource_work w
  ON w.tenant_id = s.tenant_id AND w.service_id = s.id
WHERE s.tenant_id = $1 AND s.id = $2
  AND w.lease_token = $3
  AND w.lease_until > clock_timestamp()
`

type GetLeasedDesiredParams struct {
	TenantID   pgtype.UUID
	ID         pgtype.UUID
	LeaseToken pgtype.UUID
}

type GetLeasedDesiredRow struct {
	TenantID          pgtype.UUID
	ID                pgtype.UUID
	DesiredGeneration int64
}

// A runtime worker must re-read the desired generation while holding its
// PostgreSQL lease.  An event or stale in-memory item cannot authorize work.
func (q *Queries) GetLeasedDesired(ctx context.Context, arg GetLeasedDesiredParams) (GetLeasedDesiredRow, error) {
	row := q.db.QueryRow(ctx, getLeasedDesired, arg.TenantID, arg.ID, arg.LeaseToken)
	var i GetLeasedDesiredRow
	err := row.Scan(&i.TenantID, &i.ID, &i.DesiredGeneration)
	return i, err
}

const getResourceWork = `-- name: GetResourceWork :one
SELECT tenant_id, service_id, dirty_version, acknowledged_version, next_run_at,
       attempt, lease_owner, lease_until, lease_token, last_error_code, updated_at
FROM inference_resource_work
WHERE tenant_id = $1 AND service_id = $2
`

type GetResourceWorkParams struct {
	TenantID  pgtype.UUID
	ServiceID pgtype.UUID
}

func (q *Queries) GetResourceWork(ctx context.Context, arg GetResourceWorkParams) (InferenceResourceWork, error) {
	row := q.db.QueryRow(ctx, getResourceWork, arg.TenantID, arg.ServiceID)
	var i InferenceResourceWork
	err := row.Scan(
		&i.TenantID,
		&i.ServiceID,
		&i.DirtyVersion,
		&i.AcknowledgedVersion,
		&i.NextRunAt,
		&i.Attempt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseToken,
		&i.LastErrorCode,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueResourceWork = `-- name: ListDueResourceWork :many
SELECT w.tenant_id, w.service_id, w.dirty_version, s.desired_generation
FROM inference_resource_work w
JOIN inference_services s
  ON s.tenant_id = w.tenant_id AND s.id = w.service_id
WHERE w.tenant_id = $1
  AND s.deleted_at IS NULL
  AND (w.lease_until IS NULL OR w.lease_until <= clock_timestamp())
  AND (
    (w.next_run_at IS NOT NULL AND w.next_run_at <= clock_timestamp())
    OR (w.next_run_at IS NULL AND w.acknowledged_version < w.dirty_version)
  )
ORDER BY w.next_run_at NULLS FIRST, w.updated_at, w.service_id
`

type ListDueResourceWorkRow struct {
	TenantID          pgtype.UUID
	ServiceID         pgtype.UUID
	DirtyVersion      int64
	DesiredGeneration int64
}

// This is a recovery/periodic scan.  The tenant predicate is mandatory so a
// caller cannot accidentally turn a tenant worker into a cross-tenant queue.
func (q *Queries) ListDueResourceWork(ctx context.Context, tenantID pgtype.UUID) ([]ListDueResourceWorkRow, error) {
	rows, err := q.db.Query(ctx, listDueResourceWork, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueResourceWorkRow
	for rows.Next() {
		var i ListDueResourceWorkRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ServiceID,
			&i.DirtyVersion,
			&i.DesiredGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantScopes = `-- name: ListTenantScopes :many
SELECT DISTINCT tenant_id
FROM inference_services
WHERE deleted_at IS NULL
ORDER BY tenant_id
`

// Platform worker entry: this is the sole cross-tenant discovery query. Each
// returned scope is passed to tenant-scoped Claim/Scan methods afterwards.
func (q *Queries) ListTenantScopes(ctx context.Context) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listTenantScopes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tenant_id pgtype.UUID
		if err := rows.Scan(&tenant_id); err != nil {
			return nil, err
		}
		items = append(items, tenant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndeletedServices = `-- name: ListUndeletedServices :many
SELECT tenant_id, id, desired_generation
FROM inference_services
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY updated_at, id
`

type ListUndeletedServicesRow struct {
	TenantID          pgtype.UUID
	ID                pgtype.UUID
	DesiredGeneration int64
}

// Startup recovery uses this list to repair a missing resource_work row before
// the normal due scan.  It remains explicitly tenant-scoped.
func (q *Queries) ListUndeletedServices(ctx context.Context, tenantID pgtype.UUID) ([]ListUndeletedServicesRow, error) {
	rows, err := q.db.Query(ctx, listUndeletedServices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUndeletedServicesRow
	for rows.Next() {
		var i ListUndeletedServicesRow
		if err := rows.Scan(&i.TenantID, &i.ID, &i.DesiredGeneration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryResourceWork = `-- name: RetryResourceWork :execrows
UPDATE inference_resource_work w
SET next_run_at = clock_timestamp() + $1::double precision * interval '1 second',
    lease_owner = NULL, lease_until = NULL, lease_token = NULL,
    last_error_code = $2, updated_at = clock_timestamp()
FROM inference_services s
WHERE w.tenant_id = $3 AND w.service_id = $4
  AND s.tenant_id = w.tenant_id AND s.id = w.service_id
  AND s.deleted_at IS NULL
  AND s.desired_generation = $5
  AND w.lease_token = $6
  AND w.lease_until > clock_timestamp()
`

type RetryResourceWorkParams struct {
	RetrySeconds      float64
	ErrorCode         string
	TenantID          pgtype.UUID
	ServiceID         pgtype.UUID
	DesiredGeneration int64
	LeaseToken        pgtype.UUID
}

func (q *Queries) RetryResourceWork(ctx context.Context, arg RetryResourceWorkParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryResourceWork,
		arg.RetrySeconds,
		arg.ErrorCode,
		arg.TenantID,
		arg.ServiceID,
		arg.DesiredGeneration,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
